### ISSUE TITLE
`str_sub <- (replacement)`; length(replacement)>1

### ISSUE THREAD

**Issue by mirmalis** [tidyverse/stringr#123]
The first example in [stringr vignette](/stringr/vignettes/stringr.Rmd) in **Functions that return lists section**  does not return correct or at least the same results as second method for the same example.

From what I understand the problem arises from bug in `str_sub(string, loc) <- hex` assignment  where `length(hex) >= 1`. Instead of returning _string_ with two replaced regions it returns two strings with 1 replacement each.
#### Example:

``` R
> string <- "Roses are red, violets are blue"
> loc <- str_locate_all(string, 'red|blue')[[1]]
> str_sub(string, loc) <- c('1111111', '22222222')
> string
[1] "Roses are 1111111, violets are blue" "Roses are red, violets are 22222222"
```

**Comment by gagolews** [comment]
This is a correct behavior, concordant with the philosophy of vectorization. Yet, stringi/#30 addresses an enhancement that will enable `stri_sub` to accept lists of indexes. I will add this feature when I'm back from vacations.

**Comment by hadley** [comment]
The vignette has been considerably updated so that bad example no longer exists.
