### ISSUE TITLE
stringr::str_sub unexpected output with negative argument

### ISSUE THREAD

**Issue by dfalbel** [tidyverse/stringr#126]
See this minimal example:

```
set.seed(100)
a <- sample(1:10, 10000, replace = T)
res <- "ábc" %>% str_sub(start = -a)
sum(ifelse(a > 3, 3, a) != str_length(res))
[1] 2504
```

In this code, I would expect the resulting sum to be 0 instead of 2504. This is because the maximum length of the substring is 3 and otherwise `length(substring)` is equal to the value of `a`.

This only happened for inputs with special characters.

I've also opened [this question in SO](http://stackoverflow.com/q/39209945/3297472)

**Comment by dfalbel** [comment]
This is related to this: https://github.com/gagolews/stringi/issues/227

**Comment by gagolews** [comment]
Indeed, bug on the `stringi` side.

**Comment by hadley** [comment]
Closing, since this is a stringi bug
