### ISSUE TITLE
No scrollbar for long character vector input of str_view

### ISSUE THREAD

**Issue by dracodoc** [tidyverse/stringr#127]
When I used `str_view` on a long character vector, the RStudio viewer pane didn't have the scroll bar to see full content of output. I have to open it as separate html to see all output.

**Comment by hadley** [comment]
I'd say this is outside the scope of `str_view()` for now.

**Comment by petervangalen** [comment]
I just wanted to add that in my opinion the lack scrolling ability severely limits the use of str_view(), as it only allows me to see the top ~20 vector elements.
