### ISSUE TITLE
Drop-in replacement for grep

### ISSUE THREAD

**Issue by Robinlovelace** [tidyverse/stringr#129]
I assume there's a good reason why this seems not to have been done. However, I can't see it and think it would make it easier for people used to base regex to switch. `str_which()` could be a good option. Could put in a PR but wanted to check if this is something that would be useful. 

``` r
grep("z", letters)
## [1] 26
```

``` r
 which(str_detect(letters, "z"))
## [1] 26
```

Context:

http://stackoverflow.com/questions/37996050/stringr-equivalent-to-grep/38012671?noredirect=1#comment66496080_38012671

https://github.com/csgillespie/efficientR/pull/152/commits/53c96435bf5778faf7243fb95f24b546df41d6bf

**Comment by hadley** [comment]
Why do you want indices though? I think it's usually a mistake to want them, and in general, you're better off making it explicit by using `which` (although `str_which()` might possible be a good name)

**Comment by hadley** [comment]
@gagolews there's no existing equivalent of this in stringi, right?

**Comment by Robinlovelace** [comment]
Just for ease of use on the UI - many people discover `grep()` before they discover `grepl()` (based on my own experience and teaching). So I think a drop-in replacement would be used, especially by beginners. Just a use-ability thing and totally agree non indexed version is generally better.

**Comment by gagolews** [comment]
@hadley it's on a to-do list, https://github.com/gagolews/stringi/issues/90

**Comment by Robinlovelace** [comment]
Thanks!
