### ISSUE TITLE
last_index_of

### ISSUE THREAD

**Issue by simonthelwall** [tidyverse/stringr#130]
Apologies if this has already been requested, I did search and found nothing. 
It would be great if stringr had a `last_index_of` function so that in inconsistently-formatted urls, I could do `str_extract()` from the last `/` to the end of the url in a simple manner. 
[R.oo](http://www1.maths.lth.se/matstat/bioinformatics/software/R/library/R.oo/html/String.lastIndexOf.html) has some nice examples:

```
   s <- new(String("Hello world!"))
   s$lastIndexOf(" ")               # 5
```

**Comment by gagolews** [comment]
stringi has `stri_locate_last_regex`, among others...

**Comment by hadley** [comment]
Yeah, you'll need to use stringi for the last variants.
