### ISSUE TITLE
stopping at first occurrency

### ISSUE THREAD

**Issue by skanskan** [tidyverse/stringr#131]
When working with vectors it would be great if functions such as str_detect had the option to stop when the first occurrency happen.
(Like  grep -m parameter).

That would make many operations much faster, such as quickly detecting columns containing some string.

I've also asked the same for base R grep, but I guess they will need years to do it.

**Comment by gagolews** [comment]
sounds like a nice idea; pls add this issue to gagolews/stringi - we will discuss this FR there

**Comment by skanskan** [comment]
I did it.
