### ISSUE TITLE
str_c does not work with single backslash separator

### ISSUE THREAD

**Issue by nirmalpatel** [tidyverse/stringr#132]
Hi, I'm just reporting a small issue with str_c function. It does not work with a single backslash separator.

R version: 3.3.1
stringr version: 1.1.0

```
library(stringr)
str_c("x", "y", sep="/") # Works
str_c("x", "y", sep="\\") # Separates with double backslash
str_c("x", "y", sep="\") # Expects more input with a + sign in console
```

**Comment by gagolews** [comment]
`"\"` is not a legal string in R -- will never work, see `?Quotes`

**Comment by nirmalpatel** [comment]
Thanks for the explanation. I'll close the issue.
