### ISSUE TITLE
str_replace() alters order of intended replacement string

### ISSUE THREAD

**Issue by Myfanwy** [tidyverse/stringr#133]
I have a dataframe `d` with a column `Station` where I wanted to make the following replacement:

```
d$Station <- str_replace(d$Station, 'YB_BCE2', 'BC2_joint') 

sort(unique(d$Station))[1:5]
[1] "Base_TD"      "BC_joint"     "BC_joint2"    "Decker_IsCL3" "Decker_IsCR2"
```

So instead of replacing string with the intended value (`'BC2_joint'`), it replaced it with `'BC_joint2'`.  Any ideas why it would move the 2 to the end?

Thanks!

**Comment by gagolews** [comment]
And the original `d$Station` is like.... ?

**Comment by Myfanwy** [comment]
Sorry, the original `d$Station` has 65 unique stations, but the stations of interest for renaming are initially at the tail end of the column in the dataframe `d`:
```
 tail(sort(unique(d$Station)))
[1] "Turner_Cut_2"     "YB_BCE"           "YB_BCE2"          "YB_BCW"          
[5] "YB_BCW2"          "YB_ToeDrain_Base"
```

I can successfully replace Stations `"YB_BCE"` and `"YB_BCW"` with `"BC_joint"`.  I'd like to also replace both Stations `"YB_BCE2"` and `"YB_BCW2"` with "`BC2_joint`".   I just gave the one replacement in the issue above as an example, but other replacement line is:

```
d$Station <- str_replace(d$Station, 'YB_BCW2' , 'BC2_joint')
```
After running, these two replacements both return `BC_joint2`.  I just didn't know why it moved the 2 to the other side of the string.

```
> head(sort(unique(d$Station)))
[1] "Base_TD"      "BC_joint"     "BC_joint2"    "Decker_IsCL3" "Decker_IsCR2"
[6] "Decker_IsSE"
```
