### ISSUE TITLE
Error in finding stringr

### ISSUE THREAD

**Issue by ktdesignbox** [tidyverse/stringr#135]
I have only been capable of firing up this library once. All the times after that, the same message appears, as if the package was never installed. However, it is shown in the Rstudio package window. 

Error in FUN(X[[i]], ...) : 
  cannot open file '~/R/win-library/3.3/stringr/data/Rdata.rdb': No such file or directory
In addition: Warning message:
In FUN(X[[i]], ...) : restarting interrupted promise evaluation

**Comment by hadley** [comment]
I'd recommend restarting R and reinstalling stringr.
