### ISSUE TITLE
Preserve valid HTML?

### ISSUE THREAD

**Issue by jonocarroll** [tidyverse/stringr#139]
I love `stringr::str_view_all` -- it's my go-to `regex` checker (in concert with `rex()` and RStudio). I noticed recently though that I wasn't getting any output on a call. The reprex being:
```
string <- '<a href="http://example.com"></a>'
stringr::str_view_all(string, "http")
```
I eventually realised that the HTML was being parsed for rendering in the Viewer, and in this case there's nothing to render. This isn't the desired behaviour, particularly if one is trying to view/regex match on the HTML source.

A slightly longer example:
```
string <- '<a href="http://example.com">this is a test link</a>'

stringr::str_view_all(string, "link") ## renders HTML, highlights 'link'
stringr::str_view_all(string, "http") ## renders HTML incorrectly, no highlight
```
One *could* just do the escaping themselves:
```
stringr::str_view_all(URLencode(string), "link") ## escapes HTML, highlights 'link'
stringr::str_view_all(URLencode(string), "http") ## escapes HTML, highlights 'http'
```
but this isn't pretty, and introduces `%20`s everywhere. Should `str_view` perhaps handle this and present the string as-is somehow? I get that the highlighting is performed via a `span` class but shouldn't there be some escaping?

**Comment by hadley** [comment]
Related to #128 

I think this is moderately hard to implement but I'll take a look the next time I'm working on stringr.

**Comment by rafalab** [comment]
A simpler example that I think is related to this issue are leading whitespace. Take a look:

`stringr::str_view(c(" 1", "1"), "^\\d$")`

This shows the right thing:

`stringr::str_view(c("&nbsp1", "1"),  "^\\d$")`

Adding this at the start:

`string <- str_replace_all(string, "^\\s", "&nbsp")`

might do it.

**Comment by hadley** [comment]
I think I'm going to switch to a system based on ANSI escapes (#370) which should avoid this problem altogether.
