### ISSUE TITLE
unable to execute the str_to_upper, str_to_lower, str_to_title

### ISSUE THREAD

**Issue by DhivyaRakesh** [tidyverse/stringr#140]
I'm unable to execute the commands using  str_to_upper, str_to_lower, str_to_title , though I have the stringr installed.

Please let me know if I have missed out on something as am new to R

**Comment by gagolews** [comment]
If you feel like this is a bug, please provide a reproducible example.
Otherwise, use, e.g., StackOverflow to get help on using stringr.
