### ISSUE TITLE
str_replace encoding

### ISSUE THREAD

**Issue by danielsjf** [tidyverse/stringr#143]
Using € signs has strange effects in combination with str_replace.

    text <- '€50$'
    text # [1] "€50$"
    str_replace(text, '50', '100') # [1] "\u0080100$"
    str_replace(text, '[$]', '€') # [1] "\u008050\u0080"

It seems that he changes the encoding:

    Encoding(text) # 'latin1'
    Encoding(str_replace(text, '50', '100')) # 'UTF-8'

However, resetting the encoding does not solve my problem:

    replacement <- str_replace(text, '50', '100')
    Encoding(replacement)
    Encoding(replacement) <- 'latin1'
    Encoding(replacement)
    replacement

**Comment by gagolews** [comment]
Yes, the encoding is changed to UTF-8. It is a feature of `stringi`, not a bug, see `?"stringi-encoding"` for full discussion.
What would you want to work with latin1? R seamlessly supports both UTF-8 and your native encoding.

**Comment by gagolews** [comment]
Moreover, use, e.g., `stri_encode` for character encoding conversion, and not the `Encoding<-` fun call - it's only used for enc marking, not re-encoding of char streams

**Comment by danielsjf** [comment]
Yes that's the strange part. I just noticed the strange behaviour of str_replace. I've never set anything to latin1. I've checked and RStudio is set to UTF-8. I've added the results that I see after the commands in the original post.

**Comment by danielsjf** [comment]
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] stringr_1.1.0

loaded via a namespace (and not attached):
[1] magrittr_1.5  tools_3.3.2   stringi_1.1.2

**Comment by danielsjf** [comment]
I did some more testing and found these differences:

```
# euro sign from definition (http://www.fileformat.info/info/unicode/char/20aC/index.htm)
> euro_sign_utf8_def <- rawToChar(as.raw(c('0xE2', '0x82', '0xAC')))
> euro_sign_utf8_def
[1] "â‚¬"
> Encoding(euro_sign_utf8_def) <- 'UTF-8'
> euro_sign_utf8_def
[1] "€"

# euro sign from text
> euro_sign_text <- '€'
> euro_sign_text
[1] "€"

# euro sign from string replace conversion
> euro_sign_str_rep <- str_replace(euro_sign_text, ' ', ' ')
> euro_sign_str_rep
[1] "\u0080"

> charToRaw(euro_sign_utf8_def)
[1] e2 82 ac
> charToRaw(euro_sign_text)
[1] 80
> charToRaw(euro_sign_str_rep)
[1] c2 80
```

So apparently the function str_replace yields a different result than the euro sign according to the  definition.

**Comment by gagolews** [comment]
This issue is related to stringi, not stringr, file an issue at https://github.com/gagolews/stringi/issues
