### ISSUE TITLE
str_match_all and regex(..., multiline = TRUE)

### ISSUE THREAD

**Issue by dhicks** [tidyverse/stringr#145]
I'm trying to remove all of the javascript from some HTML files.  The most straightforward way to do this is to match (and ultimately replace) all of the code between a `<script` and a `</script>`.  However, since the javascript I'm trying to remove is often written over multiple lines, I need multiline matching (and ultimately replacing).  

First I tried basic `str_match_all`, which didn't work:  
```
text <- "<em>matched</em><em>not \n matched</em>"
str_match_all(text, "<em>.*</em>")
```
Doing some searching around, I remembered that the default grep behavior stops at newlines.  Further digging suggests the `regex` function will change that behavior:  
```
text <- "<em>matched</em><em>not \n matched</em>"
str_match_all(text, regex("<em>.*</em>", multiline = TRUE))
```
This returns exactly the same results as the first block.  

Aside: I recognize this could be done using `xml2`.  However, since the text I'm getting at isn't located in any consistent place (e.g., it's not all in <p> tags) it seemed more efficient to read the files as single strings, then remove the javascript and all of the HTML tags.

**Comment by gagolews** [comment]
In `stringi` the option (see `?stri_regex_opts`) you are looking for is called `dotall`.

```
> stri_match_all_regex(text, "<em>.*</em>", dotall=TRUE)
[[1]]
     [,1]                                     
[1,] "<em>matched</em><em>not \n matched</em>"
```

**Comment by dhicks** [comment]
Thanks, that solves my problem.  It's still not clear to me why `multiline = TRUE` didn't have the same effect, though.
