### ISSUE TITLE
Replacing all accents

### ISSUE THREAD

**Issue by skanskan** [tidyverse/stringr#149]
Is there any stringr or stringi function or simple way to replace all accents/diactritics from a string with the plain version of the letter?

For example
soñar -> sonar
camión -> camion
égoïste  ->  egoiste

I'm looking for a single command to do it, instead of having a large list of possible changes.

**Comment by hadley** [comment]
``` r
x <- c("soñar", "camión", "égoïste")
stringi::stri_trans_general(x, "Latin-ASCII")
#> [1] "sonar"   "camion"  "egoiste"
```

**Comment by DaniMori** [comment]
Are there plans to expose `stringi::stri_trans_general()` in the {stringr} interface?
