### ISSUE TITLE
str_match/str_extract cannot support chinese well with Lookbehind assertions

### ISSUE THREAD

**Issue by jerryfuyu0104** [tidyverse/stringr#153]
stringr::str_match("aabbaa", "(?<=a)b")
stringr::str_match("aabbaa", "(?<=aa)b")
stringr::str_match("新新bbaa", "(?<=新)b")
above three got "b" correctly
stringr::str_match("新新bbaa", "(?<=新新)b")
but this got NA

replace str_match with str_extract, this situation will recur again.

**Comment by gagolews** [comment]
This is related to a bug in ICU, see https://github.com/gagolews/stringi/issues/147.
You may close the issue here, as it is `stringi`-related.
