### ISSUE TITLE
[Feature Request] add a new function: str_remove 

### ISSUE THREAD

**Issue by sibojan** [tidyverse/stringr#155]
Right now, I think that we can use str_replace to assign NA to unwanted strings.

However,   **str_remove** will be more intuitive to be used to remove specific patterns from a text string.

Thank you.

**Comment by hadley** [comment]
This seems a bit too special purposed for stringr to me. You can already use `ifelse` or subset assignment.

**Comment by Shians** [comment]
Could this be reconsidered? I think str_remove would be a good alias for `str_replace_all(string, pattern, "")`. I think it's nicer to use 

`str_extract(string, "bleh(goodstuff)") %>% str_remove("bleh")`

over

`str_match(string, "bleh(goodstuff)")[2]` 

often for things that are structure liked

```
fakenam3, ID100
h4rryp0tter. ID101
...
```

if only the ID number needs to be extracted. I understand that the ID number can still be extracted with `[0-9]+$` but having `str_remove` is less verbosity and cognitive burden for all the variations of such string formats.
