### ISSUE TITLE
POSIX or Perl style for stringr

### ISSUE THREAD

**Issue by sibojan** [tidyverse/stringr#156]
That might be more relevant for advanced users. Hope to get authors' clarification.

The default setting for most R basic string functions is POSIX 1003.2. (http://astrostatistics.psu.edu/su07/R/html/base/html/grep.html).  How about **stringr**?

**Comment by hadley** [comment]
It's not possible to change because we use a different reg ex engine, as documented at http://stringr.tidyverse.org/articles/regular-expressions.html

**Comment by sibojan** [comment]
Thank you for your reply. I am not looking at Stringr to change the reg ex engine. Instead, I am learning which standard it follows. I checked the link you posted (http://stringr.tidyverse.org/articles/regular-expressions.html).  It says **Regular expressions are the default pattern engine in stringr** .  It is still unclear that which engine is used since the Regular expressions has a number of varieties, e.g. POSIX, DFA.
