### ISSUE TITLE
surprising behvaior in str_detect

### ISSUE THREAD

**Issue by yeedle** [tidyverse/stringr#160]
This is more a question than an issue, but this is as good a place to ask as any.

I'm confused by the str_detect behavior of having string vectors and pattern vectors cycled over each other. While this makes sense when you supply one string and many patterns or one pattern and many strings, this causes surprising and non-intuitive results when many strings and many patterns are supplied. 

A much more intuitive and useful behavior would be to search for every pattern in every strings and return true if there's any match (or give the option if requiring `all` or `any` to be true). If this is not the intended behavior of str_detect, perhaps it should be added as a condition to the function, or at the very least be mentioned in the documentation.

**Comment by david-jankoski** [comment]
I've noticed the same and i agree with you that the help page could be a bit more explanatory on this - however, i believe the "hidden hints" in the help section are that the Value is a logical vector (which would be difficult to interpret in the case you are mentioning where it makes more sense to return a matrix) & the examples include cases where either `string` or `pattern` is a vector.

**Comment by hadley** [comment]
This is a fundamental feature of stringr, and there's no way to change it without breaking a heap of existing code.

The docs do say "Vectorised over \code{string} and \code{pattern}."
