### ISSUE TITLE
str_to_title() output changed from version 1.1.0 -> 1.2.0

### ISSUE THREAD

**Issue by novakowd** [tidyverse/stringr#161]
In Version 1.1.0:
```
str_to_title("This.Value")
"This.Value"
```

In Version 1.2.0:
```
str_to_title("This.Value")
"This.value"
```

i.e. The Letter after the punctuation is converted to lower case in the new version, which did not occur in the previous version.

**Comment by hadley** [comment]
It's not clear that the new behaviour is wrong, and stringr relies on stringi for this transformation.
