### ISSUE TITLE
str_extract 'locks' R, with specific combination of string and pattern

### ISSUE THREAD

**Issue by thorvall** [tidyverse/stringr#166]
Got a problem with parsing a file wit str_extract. It's locks R.
The regex works with other strings and with grep, and str_extract  on the string works with a simpler regex
I'm on a windows platform, and i crashed in both rstudio and pure R (3.4)
Reproducible example:
```
 library(stringr)
x <- c("BDSr;i2;NAmGITS;","BDx;i106;Si18;s2;SYmNC;NAmNASDAQ OMX Commodities;CNyNO;MIcNORX;","BDm;i672;Si018171;s2;Ex106;NAmFuel Oil;SYmNCFO;TOTa+0200;LDa20141011;","BDIs;i10142;SiNP;s2;ISsNP;NAmNord Pool ASA;","BDt;i122745;SiSPO380FOSS_JAN18;s2;Ex106;Mk672;INiNCFOEFCSP380F;SYmSPO380FOSS_JAN18;NAmFuel Oil Month Future;ISnNONK00309801;ISi10142;ISsNP;CUiUSD;CUtUSD;PRt1;VOd1;LDa20141218;Cf1;TTd20180131;IEtFuel Oil 380 CST FOB Cargoes Singapore;NMv0.01;ITSz275;NDp4;MPmN;MPaN;NDTp4;ITStN;STy2;AUmY;TRaY;INrN;PTaY;PTb1;OXCl0;RLoY;IaN;FxN;IqN;TUsN;LSz100;")
x <- as.list(x)
x  %>% .[grep("([A-Z]*[a-z]{1};)([A-Z]*[a-z]{1}.*;)*(i[0-9]+;){1}",.,)] -> b # works
y <- x[1:4]
str_extract(y, "([A-Z]*[a-z]{1};)([A-Z]*[a-z]{1}.*;)*(i[0-9]+;){1}") -> d # Works
y <- x[5]
b <- str_extract(y, "[aeiou]") # works
str_extract(y, "([A-Z]*[a-z]{1};)([A-Z]*[a-z]{1}.*;)*(i[0-9]+;){1}") -> d # Lock's R
```

**Comment by gagolews** [comment]
Please refer to *Peformance tips* in http://userguide.icu-project.org/strings/regexp

**Comment by thorvall** [comment]
But why then does grep work without problem on the same string. It does this matching on 95k lines in less than a second, so can't see why the same expression would cause an infinite loop on str_extrtact but not with grep.
Please enlighten me?

**Comment by gagolews** [comment]
`grep()`, `grep(perl=TRUE)`, and stringr/string rely on 3 different algorithms; see https://github.com/qinwf/re2r and the links therein. HTH

**Comment by thorvall** [comment]
@gagolews Thanks.
