### ISSUE TITLE
Behaviour of str_detect when pattern contains an empty string

### ISSUE THREAD

**Issue by etienne-s** [tidyverse/stringr#171]
Is the following behaviour consistent?

```r
str_detect("foo", "")
# [1] TRUE

str_detect("foo", c("f", ""))
# [1] TRUE   NA
# Warning message:
# In stri_detect_regex(string, pattern, opts_regex = opts(pattern)) :
#   empty search patterns are not supported

str_detect("", "")
# [1] FALSE
```

I don't get why we obtain `NA` and a warning only in the second case, am I missing something?

I'm also slightly surprised by the `FALSE` output in the third case.

**Comment by gagolews** [comment]
Try the same with `stringi`'s `stri_detect_fixed`, `stri_detect_regex`, and `stri_detect_coll` and if these inconsistencies are found, report an issue at gagolews/stringi

**Comment by etienne-s** [comment]
@gagolews I've just tried, there are non inconsistencies in `stringi`: it always returns `NA` and  throws a warning.

**Comment by gagolews** [comment]
Thanks! The problem is likely to be on the stringr side then

**Comment by hadley** [comment]
stringr has different behaviour for a single empty string vs a character vector than contains an empty string. The docs say `An empty pattern, "", is equivalent to \code{boundary("character")}.`
