### ISSUE TITLE
unexpected behavior in str_replace_all (can't remove repeated)

### ISSUE THREAD

**Issue by shapiromatron** [tidyverse/stringr#173]
When trying to clean-up NaN values from an CSV, I found that ``str_replace_all`` didn't work as expected when two matches are beside each other:

```R    
> packageVersion('stringr')
[1] ‘1.2.0’

> stringr::str_replace_all("1,NaN,NaN,2", ",NaN,", ",null,")
[1] "1,null,NaN,2"
```

You can see the first NaN is replaced with null, but the second is not. Is this expected behavior? Or do I need to specify a different search pattern?

**Comment by Monduiz** [comment]
I have found a similar behaviour:

This works:
    
    str_replace_all("Its pricy $$$$$", "\\$", "")

But this does not:
    
    str_replace_all("Its pricy $$$$$", "[[:punct:]]", "")

**Comment by gagolews** [comment]
RTM, refer to ?"stringi-search-charclass" in stringi

**Comment by hadley** [comment]
@shapiromatron It's basically because the match is always advanced after replacement (i.e. character in the replacement are never considered part of the match)
