### ISSUE TITLE
Feature request - add internal option to str_pad

### ISSUE THREAD

**Issue by simonthelwall** [tidyverse/stringr#176]
`str_pad()` currently expands white space to the left and/or right of a string. I'd really like to see an internal option added to this so that white space is used to fill in between words, up to the desired number of characters. 

My use case is normalising postcodes. I have postcode strings 6, 7 and 8 characters long that are two words separated by white space. I need to add white space between the two so that they are all 8 characters long. 

Thanks!

**Comment by hadley** [comment]
Sorry, that's out of scope for stringr. I'd prefer not to get into all the possible ways you might justify a string!

**Comment by yutannihilation** [comment]
@simonthelwall FYI: stringi has a TODO for this. https://github.com/gagolews/stringi/issues/73 (It seems not going to be implemented, though.)
