### ISSUE TITLE
Typo Fixing in raw-data

### ISSUE THREAD

**Issue by bpasanek** [tidyverse/stringr#182]
In stringr version 1.2.0 `sentences[593]` returns
`[593] "Slidc the tray across the glass top."  `

I assume that's supposed to be "Slide". 

Looks like this is still the case in the data-raw/harvard-sentences.txt

Some others:
`[385] "Fake &ones shine but cost little." `
`[439] "Xew pants lack cuffs and pockets." `
`[536] "Cheap clothes are flashy but don??????t last."`
`[565] "The hilt. of the sword was carved with fine designs."`
`[624]` "The facts don\u0092t always show who is right."
`[636] "Pack the kits and don\u0092t forget the salt."`

Thanks for providing these in the package! Hope the stickling call for typo fixing is welcome!

**Comment by hadley** [comment]
Thanks for the bug report!
