### ISSUE TITLE
str_pad count 1 chinese char as 2

### ISSUE THREAD

**Issue by frootor** [tidyverse/stringr#188]
> vchs= "中,中中,中中中"
> yc=str_split(vchs,",",simplify = T)
> print(yc)
     [,1] [,2]   [,3]    
[1,] "中" "中中" "中中中"
> yl=str_length(yc)
> print(yl)
[1] 1 2 3
> print(max(yl))
[1] 3
> ycd=stringr::str_pad(yc,width=max(str_length(yc)),side = "right",pad=" ")
> ycd
[1] "中 "    "中中"   "中中中"
> ycd=stringr::str_pad(yc,width=2*max(str_length(yc)),side = "right",pad=" ")
> ycd
[1] "中    " "中中  " "中中中"

**Comment by frootor** [comment]
str_pad <- function(string, width, side = c("left", "right", "both"), pad = " ") {
  side <- match.arg(side)

  switch(side,
    left = stri_pad_left(string, width, pad = pad),
    right = stri_pad_right(string, width, pad = pad),
    both = stri_pad_both(string, width, pad = pad)
  )
}

# here is the reason ------

stri_pad(str, width = floor(0.9 * getOption("width")), side = c("left",
  "right", "both"), pad = " ", use_length = FALSE)

use_length | single logical value; should the number of code points be used instead of the total code point width (see stri_width)

**Comment by frootor** [comment]
str_pad<- function(string, width, side = c("left", "right", "both"), pad = " ") {
    side <- match.arg(side)
    
    switch(side,
        left = stri_pad_left(string, width, pad = pad,**use_length = T**),
        right = stri_pad_right(string, width, pad = pad**,use_length = T**),
        both = stri_pad_both(string, width, pad = pad**,use_length = T**)
    )
}

**Comment by yutannihilation** [comment]
Hi, let me comment on this as this feature is added by my request on stringi's side (https://github.com/gagolews/stringi/issues/149).

I believe it is fine to pad based on their widths most of the time, assuming the main use case of padding is to arrange strings prettier with the proper number of white spaces:

``` r
reprex::reprex_info()
#> Created by the reprex package v0.1.1.9000 on 2017-11-06

library(stringr)

c("中", "中中", "中中中") %>%
  str_pad(width = 10) %>%
  cat(sep = "\n")
#>         中
#>       中中
#>     中中中
```

That said, it may be useful to specify `use_length` from stringr's function for some cases. I will create a PR.

**Comment by hadley** [comment]
@frootor can you clarify why you need this?

**Comment by frootor** [comment]
in chinse,there is a full with（全角） space "　"  and a half width（半角） space " "。
if i want to pad chinese string to the same width,using a full width sapce "　" is a better choice, for in this case the width and the length are both the same. if use a half width space " " to pad the same width, the strings length are not the same ,for 2 half width space equal the length of a chinese char.
so for a simple logic to handle such problem , add a "use_length" param maybe better.

**Comment by frootor** [comment]
when using Rgraphviz,i want to pad the node label to the same length and the same width, but str_pad fail to  handle it in default way ,then i found this issue.

**Comment by frootor** [comment]
if not add "use_length", when use str_pad to handle chinese string ,chinese char should count  2 ,then str_pad  works, but usually we count a chinese char as 1.

**Comment by yutannihilation** [comment]
> if use a half width space " " to pad the same width, the strings length are not the same ,for 2 half width space equal the length of a chinese char.

Ah, this is true if the font is not monospace.

Still, I wonder the option is really useful for you. You cannot use full-width whitespace "　"(U+3000, IDEOGRAPHIC SPACE) for padding. How will use `use_length` to solve your problem?

```r
stringr::str_pad(c("中", "中中", "中中中"), width = 6, pad = "\u3000")
#> Error in stri_pad_left(string, width, pad = pad, use_length = use_length) : 
#>   each string in `pad` should consist of code points of total width 1
```

I think you can either:

1. use some monospace font (e.g. [Noto Sans Mono CJK](https://www.google.com/get/noto/help/cjk/)) or
2. pad with half-width spaces and replace two half-width spaces with one full-width space:

```r
c("中", "中中", "中中中") %>%
  str_pad(width = 6, pad = " ") %>%
  str_replace_all("  ", "\u3000")
```

**Comment by yutannihilation** [comment]
Sorry! I misunderstood about what you are saying...

`use_length=TRUE` must be specified if we want to pad with "wide" characters.

```r
stringr::str_pad(c("中", "中中", "中中中"), width = 6, pad = "\u3000")
#> Error in stri_pad_left(string, width, pad = pad, use_length = use_length) : 
#>   each string in `pad` should consist of code points of total width 1

stringi::stri_pad_left(c("中", "中中", "中中中"), width = 3, pad = "\u3000", use_length = TRUE)
#> [1] "　　中" "　中中" "中中中"
```

It seems reasonable to add this option on stringr's side.

**Comment by frootor** [comment]
yes， i finally use stringi::stri_pad_left settle it

**Comment by hadley** [comment]
@yutannihilation I know this is rather old, but do you have any advice for stringr here? Should I just pass the `use_length` argument on to stringi?

**Comment by yutannihilation** [comment]
Yes, I think just passing `use_length` is enough, just like I did in https://github.com/tidyverse/stringr/pull/190.
