### ISSUE TITLE
Add str_capture()

### ISSUE THREAD

**Issue by nthun** [tidyverse/stringr#189]
`str_match()` returns a matrix, with the columns as the capture groups, and the first column is the whole match. I think there might be two issues about this:

1) Redundancy: the first column is the same as returned by `str_extract()`
2) Confusing: The column numbers do not match the capture group numbers, e.g. you have to refer to the first capture group as the second column `[,2]`

I guess it is not possible to change the `str_match()` function now. But maybe it would make sense to add a function (`str_capture`?) that only return the capture groups?

**Comment by hadley** [comment]
Hmmm, I think that would increase net confusion because there's now another function that differs from an existing function only by a small amount. You can always do `str_match()[-1, ]`
