### ISSUE TITLE
Dependency on htmlwidgets

### ISSUE THREAD

**Issue by jonocarroll** [tidyverse/stringr#196]
`str_view()` depends on `htmlwidgets` (and strictly `htmltools`). These are only listed in `Suggests` so they aren't installed with a standard `install.packages("stringr")`. 

I'm writing a beginners R book and part of that involves checking that my code works as a 'new user'. My `str_view()` examples don't for the above reason, despite following the `README` instructions.

<details><summary>Expand for MRE:</summary>

```r
## create a fresh library, as if just starting 
## out using R and decided to try this package first.
library(switchr)

tmp_lib <- file.path(tempdir(), ".lib")
dir.create(tmp_lib)

switchrBaseDir(tmp_lib)
switchTo("tmplib")

## install stringr as directed in the README, 
## or as otherwise standard
install.packages("stringr")
# also installing the dependencies ‘stringi’, ‘magrittr’

## try to use the functionality
library(stringr)

x <- c("abc", "def", "fgh")

## fails because no htmltools or htmlwidgets
str_view(x, "d|e")

## (clean up)
switchBack()
unlink(tmp_lib)
```
</details><br />

The [Writing R Extensions manual](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Package-Dependencies) doesn't offer the suggestion that rarely used packages should be in `Suggests`, though http://r-pkgs.had.co.nz/description.html does (with encouragement to add `requireNamespace(x, quietly = TRUE)`). I'm more familiar with `Suggests` being used when a package is only used in examples, tests or vignettes.

On trying to figure out why the `str_view()` tests pass on Travis at all, the best I can figure is that Travis setup involves `devtools::install_deps(dependencies = TRUE)` which apparently "installs dependencies in depends/links to/suggests".

What is the intended action for a new user? Installing `htmlwidgets` themselves works, but they shouldn't have to/aren't instructed to. An exported function just fails if they don't.  Should `str_view()` have some `requireNamespace` tests?

**Comment by hadley** [comment]
You currently get the error "there is no package called ‘htmlwidgets’", which should be fairly informative (except to the very new R users). Can you just tell them to explicitly install htmlwidgets too?

You could also make a package for your book that does install htmlwidgets.

**Comment by jonocarroll** [comment]
Is that standard practice though? A package could have no dependencies and rely on the user to respond to "there is no package called ‘x’" for everything. In this case the user actually gets "there is no package called ‘htmltools’" since that's the first missing dependency. After installing that, they *then* get "there is no package called ‘htmlwidgets’" too. 

A book-specific package is probably what I'll do to ensure version consistency in any case, but I would think a `if(!requireNamespace())` check in `stringr` would be welcome. A mention of this in the docs for `str_view` (and where it's used) might be a good idea.

**Comment by hadley** [comment]
I don't think this is necessary as I expect most R users to be able to install packages on demand when needed.

**Comment by hadley** [comment]
Changing my mind since we now have the nice `rlang::check_installed()`
