### ISSUE TITLE
Bug in stringr or base Packages

### ISSUE THREAD

**Issue by msgoussi** [tidyverse/stringr#201]
Dear Madam/Sir,
Greetings.
x <- "La vie en #FFC0CB (rose);\nCes't la vie! \ttres jolie"
pattern <- "[^[:print:]]"
str_view_all(x, pattern)
gsub(pattern, "", x)
[1] "La vie en #FFC0CB (rose);Ces't la vie! \ttres jolie"
str_replace_all(x, pattern, "")
[1] "La vie en #FFC0CB (rose);Ces't la vie! tres jolie"

gsub is not replacing "\t" when when using "[^[:print:]]" as pattern, also it is replacing "\n".
Thanks

Is this a bug or not, if yes, please advise.

**Comment by gagolews** [comment]
Refer to `?"stringi-search-charclass"` in the `stringi` manual.
