### ISSUE TITLE
str_to_sentence

### ISSUE THREAD

**Issue by dhodge** [tidyverse/stringr#202]
Hi, could we please have a function that converts a string to sentence case. Some code below with my attempt at this..

str_to_sentence <- function(x) {
  paste0(str_to_upper(str_sub(x, 1, 1)), str_to_lower(str_sub(x, 2)))
  }

**Comment by hadley** [comment]
stringr relies on stringi for these functions, so you'd need to get it into stringi first. 

cc @gagolews

**Comment by dhodge** [comment]
Just found this in stringi
library(stringi)
stri_trans_totitle("a Test", opts_brkiter = stri_opts_brkiter(type = "sentence"))

**Comment by wmayner** [comment]
I'd really like to have the functionality as well!

**Comment by jonthegeek** [comment]
@batpigandme I'm working on this for Tidyverse Developer Day.

**Comment by dhodge** [comment]
Thanks :)
