### ISSUE TITLE
Feature request: generalization of stringr::str_count

### ISSUE THREAD

**Issue by IndrajeetPatil** [tidyverse/stringr#204]
Hi!

I was wondering if it would be possible to have a more general version of `stringr::str_count` which doesn't assume that the string contains only letters. Please let me know if there is already a way to do this in this package.

Thanks.

P.S. I found a workaround solution to achieve this using some `C++` code, but would love it if there is a dedicated function to achieve the same thing in `stringr` since I need to share script with other people and a number of them seem to be having trouble reproducing my results because of the C compiler issues.

```
## custom function to count the number of unique characters in any given string

.char_unique_code <- "
std::vector < std::string > s = as< std::vector < std::string > >(x);
unsigned int input_size = s.size();

std::vector < std::string > chrs(input_size);

for (unsigned int i = 0; i<input_size; i++) {

std::string t = s[i];

for (std::string::iterator chr = t.begin();
chr != t.end(); ++chr) {

if (chrs[i].find(*chr) == std::string::npos) {
chrs[i] += *chr;
}

}

}
return(wrap(chrs));
"

char_unique <- rcpp(sig = signature(x = "std::vector < std::string >"),
                    body = .char_unique_code,
                    includes = c("#include <string>", "#include <iostream>"))
```

**Comment by hadley** [comment]
`str_count()` works with patterns, so you can already generalise however you like
