### ISSUE TITLE
incorrect str_extract() operation

### ISSUE THREAD

**Issue by andreypanchenko** [tidyverse/stringr#215]
Hi, today explore some bag.
Problem :  
str_extract("10 (Очень легко)","\\d") return only 1 but must return 10
at the same time 
gsub("\\D","","10 (Очень легко)") return 10
and 
parse_number("10 (Очень легко)") return 10
translate string into Englesh dont fix problem 
str_extract("10 (Very simply)","\\d") return 1

**Comment by m0nhawk** [comment]
I'm not a developer, but a long-term user of `stringr`.

`gsub` is used to replace the pattern with some placement string. Thus, the analog of `gsub("\D","","10 (Очень легко)")` is `str_replace_all("10 (Очень легко)", "\\D", "")`, which gives the correct output:

```
str_replace_all("10 (Очень легко)", "\\D", "")
# [1] "10"
```

And `str_extract` is used to extract the pattern, in this case: `\d` which is a single digit. The proper use:

```
str_extract("10 (Очень легко)","\\d+")
# [1] "10"
```
