### ISSUE TITLE
Add additional example for str_detect to show absence

### ISSUE THREAD

**Issue by mdzievit** [tidyverse/stringr#220]
The description of the function is to "Detect the presence or absence of a pattern in a string", however, there is no clear example in the "examples" section on how to detect the absence of a pattern. Maybe it is obvious/intuitive on how to do it. It took me a few tries to figure it out, but an example might save time to others in the future.

**Suggested example:**
```
fruit <- c("apple", "banana", "pear", "pinapple")
!str_detect(fruit, "r")
[1]  TRUE  TRUE FALSE  TRUE
```

**Comment by batpigandme** [comment]
I think this might be an example that illustrates the use of `!` more so than `str_detect()`, which could be confusing…

If you think about it in terms of the existing examples, what I'm demonstrating below is the logic of `!`, which isn't really a property of a stringr function…

``` r
suppressPackageStartupMessages(library(tidyverse))
fruit <- c("apple", "banana", "pear", "pinapple")
str_detect(fruit, "a")
#> [1] TRUE TRUE TRUE TRUE
str_detect(fruit, "^a")
#> [1]  TRUE FALSE FALSE FALSE
str_detect(fruit, "a$")
#> [1] FALSE  TRUE FALSE FALSE
str_detect(fruit, "b")
#> [1] FALSE  TRUE FALSE FALSE
str_detect(fruit, "[aeiou]")
#> [1] TRUE TRUE TRUE TRUE

!str_detect(fruit, "a")
#> [1] FALSE FALSE FALSE FALSE
!str_detect(fruit, "^a")
#> [1] FALSE  TRUE  TRUE  TRUE
!str_detect(fruit, "a$")
#> [1]  TRUE FALSE  TRUE  TRUE
!str_detect(fruit, "b")
#> [1]  TRUE FALSE  TRUE  TRUE
!str_detect(fruit, "[aeiou]")
#> [1] FALSE FALSE FALSE FALSE
```

Created on 2018-05-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).
