### ISSUE TITLE
Help installing tidy verse

### ISSUE THREAD

**Issue by sneweyy** [tidyverse/stringr#221]
Hello! I'm trying to use tidy verse on my Mac, with runs on MacOS High Sierra. 

I've downloaded R and R Studio, but every time I try to install tidy verse I get the following happens (see below). Does anyone know what I can do to fix this issu? 

Thank you!!!

Sarah

> install.packages("tidyverse")
also installing the dependencies ‘testthat’, ‘utf8’, ‘callr’, ‘pillar’, ‘dplyr’, ‘lubridate’, ‘purrr’, ‘reprex’, ‘rlang’, ‘tibble’, ‘tidyr’

trying URL 'https://cran.rstudio.com/src/contrib/testthat_2.0.0.tar.gz'
Content type 'application/x-gzip' length 217190 bytes (212 KB)
==================================================
downloaded 212 KB

trying URL 'https://cran.rstudio.com/src/contrib/utf8_1.1.3.tar.gz'
Content type 'application/x-gzip' length 217735 bytes (212 KB)
==================================================
downloaded 212 KB

trying URL 'https://cran.rstudio.com/src/contrib/callr_2.0.2.tar.gz'
Content type 'application/x-gzip' length 95272 bytes (93 KB)
==================================================
downloaded 93 KB

trying URL 'https://cran.rstudio.com/src/contrib/pillar_1.1.0.tar.gz'
Content type 'application/x-gzip' length 71173 bytes (69 KB)
==================================================
downloaded 69 KB

trying URL 'https://cran.rstudio.com/src/contrib/dplyr_0.7.4.tar.gz'
Content type 'application/x-gzip' length 808054 bytes (789 KB)
==================================================
downloaded 789 KB

trying URL 'https://cran.rstudio.com/src/contrib/lubridate_1.7.2.tar.gz'
Content type 'application/x-gzip' length 450988 bytes (440 KB)
==================================================
downloaded 440 KB

trying URL 'https://cran.rstudio.com/src/contrib/purrr_0.2.4.tar.gz'
Content type 'application/x-gzip' length 126147 bytes (123 KB)
==================================================
downloaded 123 KB

trying URL 'https://cran.rstudio.com/src/contrib/reprex_0.1.2.tar.gz'
Content type 'application/x-gzip' length 22879 bytes (22 KB)
==================================================
downloaded 22 KB

trying URL 'https://cran.rstudio.com/src/contrib/rlang_0.2.0.tar.gz'
Content type 'application/x-gzip' length 323899 bytes (316 KB)
==================================================
downloaded 316 KB

trying URL 'https://cran.rstudio.com/src/contrib/tibble_1.4.2.tar.gz'
Content type 'application/x-gzip' length 109808 bytes (107 KB)
==================================================
downloaded 107 KB

trying URL 'https://cran.rstudio.com/src/contrib/tidyr_0.8.0.tar.gz'
Content type 'application/x-gzip' length 377417 bytes (368 KB)
==================================================
downloaded 368 KB

trying URL 'https://cran.rstudio.com/src/contrib/tidyverse_1.2.1.tar.gz'
Content type 'application/x-gzip' length 61647 bytes (60 KB)
==================================================
downloaded 60 KB

* installing *source* package ‘utf8’ ...
** package ‘utf8’ successfully unpacked and MD5 sums checked
** libs
x86_64-apple-darwin13.4.0-clang -I/Users/sarahnewey/anaconda3/lib/R/include -DNDEBUG   -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/Users/sarahnewey/anaconda3/include  -Iutf8lite/src -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/Users/sarahnewey/anaconda3/include  -c as_utf8.c -o as_utf8.o
make: x86_64-apple-darwin13.4.0-clang: No such file or directory
make: *** [as_utf8.o] Error 1
ERROR: compilation failed for package ‘utf8’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/utf8’
Warning in install.packages :
  installation of package ‘utf8’ had non-zero exit status
* installing *source* package ‘lubridate’ ...
** package ‘lubridate’ successfully unpacked and MD5 sums checked
** libs
x86_64-apple-darwin13.4.0-clang++ -std=gnu++11 -I/Users/sarahnewey/anaconda3/lib/R/include -DNDEBUG -I. -I./cctz/include/ -I./cctz/src/ -I"/Users/sarahnewey/anaconda3/lib/R/library/Rcpp/include" -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/Users/sarahnewey/anaconda3/include   -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden  -fmessage-length=0 -I/Users/sarahnewey/anaconda3/include -c RcppExports.cpp -o RcppExports.o
/bin/sh: x86_64-apple-darwin13.4.0-clang++: command not found
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package ‘lubridate’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/lubridate’
* restoring previous ‘/Users/sarahnewey/anaconda3/lib/R/library/lubridate’
Warning in install.packages :
  installation of package ‘lubridate’ had non-zero exit status
* installing *source* package ‘rlang’ ...
** package ‘rlang’ successfully unpacked and MD5 sums checked
** libs
x86_64-apple-darwin13.4.0-clang -I/Users/sarahnewey/anaconda3/lib/R/include -DNDEBUG -I./lib/  -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/Users/sarahnewey/anaconda3/include   -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/Users/sarahnewey/anaconda3/include  -c capture.c -o capture.o
make: x86_64-apple-darwin13.4.0-clang: No such file or directory
make: *** [capture.o] Error 1
ERROR: compilation failed for package ‘rlang’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/rlang’
* restoring previous ‘/Users/sarahnewey/anaconda3/lib/R/library/rlang’
Warning in install.packages :
  installation of package ‘rlang’ had non-zero exit status
* installing *source* package ‘testthat’ ...
** package ‘testthat’ successfully unpacked and MD5 sums checked
** libs
x86_64-apple-darwin13.4.0-clang -I/Users/sarahnewey/anaconda3/lib/R/include -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT  -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -I/Users/sarahnewey/anaconda3/include   -fPIC  -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -I/Users/sarahnewey/anaconda3/include  -c init.c -o init.o
make: x86_64-apple-darwin13.4.0-clang: No such file or directory
make: *** [init.o] Error 1
ERROR: compilation failed for package ‘testthat’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/testthat’
Warning in install.packages :
  installation of package ‘testthat’ had non-zero exit status
ERROR: dependency ‘utf8’ is not available for package ‘pillar’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/pillar’
Warning in install.packages :
  installation of package ‘pillar’ had non-zero exit status
ERROR: dependency ‘testthat’ is not available for package ‘callr’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/callr’
Warning in install.packages :
  installation of package ‘callr’ had non-zero exit status
ERROR: dependency ‘pillar’ is not available for package ‘tibble’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/tibble’
Warning in install.packages :
  installation of package ‘tibble’ had non-zero exit status
ERROR: dependency ‘tibble’ is not available for package ‘dplyr’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/dplyr’
Warning in install.packages :
  installation of package ‘dplyr’ had non-zero exit status
ERROR: dependency ‘tibble’ is not available for package ‘purrr’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/purrr’
Warning in install.packages :
  installation of package ‘purrr’ had non-zero exit status
ERROR: dependency ‘callr’ is not available for package ‘reprex’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/reprex’
Warning in install.packages :
  installation of package ‘reprex’ had non-zero exit status
ERROR: dependencies ‘dplyr’, ‘purrr’, ‘tibble’ are not available for package ‘tidyr’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/tidyr’
Warning in install.packages :
  installation of package ‘tidyr’ had non-zero exit status
ERROR: dependencies ‘dplyr’, ‘purrr’, ‘reprex’, ‘tibble’, ‘tidyr’ are not available for package ‘tidyverse’
* removing ‘/Users/sarahnewey/anaconda3/lib/R/library/tidyverse’
Warning in install.packages :
  installation of package ‘tidyverse’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/k1/s0q6st716nlgjp08rf3qj8c80000gn/T/Rtmp5cgrGk/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
