### ISSUE TITLE
function "str_which" does not appear in help(package="stringr")

### ISSUE THREAD

**Issue by AndreMikulec** [tidyverse/stringr#225]
When I do
```r
help(package="stringr")
```
function 
```r
str_which 
```
does not appear.
Please, place function 
```r
str_which 
```
in the help file.

I kept using
```r
which(stringr::str_detect(.))
```
until I accidentally saw the function
```r
str_which 
```
in an unrelated example.

**Comment by hadley** [comment]
I'm not sure why you wouldn't see this, but it's in my local index.

**Comment by AndreMikulec** [comment]
@rdname seems to combine the docs of 'str_subset' and 'str_which' together 

#' @rdname str_subset

https://github.com/tidyverse/stringr/blob/e775974d2822ae0de90ab33cf9f02273c22a3801/R/subset.R

Here is str_subset.

```r
#' @export
str_subset <- function(string, pattern) {
```
Here is str_which.
```r
#' @export
#' @rdname str_subset
str_which <- function(string, pattern) {
  which(str_detect(string, pattern))
}
```

Therefore, when I do  help(package = "stringr"), then str_which does not show.
str_subset appears in help(package = "stringr")
str_subset includes the docs of both str_subset and str_which.

**Comment by hadley** [comment]
<img width="593" alt="screen shot 2018-05-09 at 8 02 35 am" src="https://user-images.githubusercontent.com/4196/39822429-5bbc51b8-535f-11e8-9b78-fe51459d74a7.png">

**Comment by AndreMikulec** [comment]
I just tried involving a new install of R, stringr, and rdoxygen2: str_which is now found in the index.

My bad for not re-verifying, not re-installing in the latest R, the latest stringr, and the latest rdoxygen2.

The problem I encountered is not *this*, below, may have been related to

@describeIn, @rdname deletes described function's documentation file #714 [https://github.com/klutometis/roxygen/issues/714](url)
