### ISSUE TITLE
Implement S3 method for summary for character vectors

### ISSUE THREAD

**Issue by olsgaard** [tidyverse/stringr#233]
Base R doesn't come with any summary method for character vectors (such as `summary.character()`). When summarizing a dataframe with character vector columns, `summary.default()` will be invoked and only the length of the column and type is displayed, which isn't a very useful to get an overview of your data.

When a user loads stringr, it is because they are interested in working with strings / character vectors and it seems reasonable to include a `summary.character()` method in this package.

Proposed summary method could include:

* Number of items 
* Number of unique items
* Longest string
* Shortest string
* Median length of string
* Number of `NA` items

Being able to easily see the relationship between total amount of items and unique number of items gives the user a good idea if the character vector should be converted into a factor.

The lengths of the strings tells the user if this is headlines/subjects/username style content, or long form content, or if there are outliers in a ID-type of column.

If there is interest for a summary method, and if stringr is the right home for such, let me know and I will prepare a pull request.

**Comment by hadley** [comment]
It is not good practice to define a method if you don't "own" either the generic or the class. That unfortunately means that this request is out of scope for stringr.
