### ISSUE TITLE
str_replace (and str_remove) applied to list should throw an error

### ISSUE THREAD

**Issue by katossky** [tidyverse/stringr#235]
It took me a very long time to spot the error here and understand why:

    library(dplyr)
    library(stringr)
    text <- "<td class=\"style7\" style=\"width: 43%\">\n        <br>\n\t\t1230  <strong>Une rentrée 2009 - Volume 1</strong><br><br><span class=\"style2\">0</span><span class=\"style131\">1 - Edward Sharpe &amp; The magnetic Zeros : 40 day \n\t\tdream<br>\n\t\t02 - Artic Monkeys : Potion approaching ( live )<br>\n\t\t03 - Air : So light is her footfall<br>\n\t\t04 - Hockey : Learn to lose<br>\n\t\t05 - The Dodos : Fables<br>\n\t\t06 - Jamie T : Hocus pocus<br>\n\t\t07 - <a href=\"Rock_Tinariwen.htm\">Tinariwen</a> : Tenhert<br>\n\t\t08 - Noah and The Whale : Blue skies<br>\n\t\t09 - Soma : Get down<br>\n\t\t10 - Florence &amp; The Machine : Howl<br>\n\t\t11 - Bad Lieutenant : Sink or swim ( radio edit )<br>\n\t\t12 - Yeti Lane : Lonesome George<br>\n\t\t13 - Coming Soon : Moonchild<br>\n\t\t14 - Paco Volume : Stand by me ( Belfast 79 )<br>\n\t\t15 - Miossec : Seul ce que j'ai perdu<br><br>\n\t\tEncarté avec le n°718 des Inrockuptibles<br>\n\t\tPhoto : Anita Ekberg dans le film \" La Dolce Vita \" ( 1960 ) - Photo \n\t\tPier Luigi</span><span class=\"style2\"><br></span>\n</td>"
    text %>% str_split("<br>") %>% str_remove_all('\n')

... was returning a super weird output (starting with `"c(\"<td class=\\\"style7\\\"...`).

It is actually because `str_split` returns a list and that `str_replace_all` weirdly handle a list by parsing it (!). I guess that throwing an error would be a better behaviour.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session. It would also help if you made the example as simple as possible.

**Comment by hadley** [comment]
Oh it turns out that this is stringi behaviour, and the latest version throws a warning.
