### ISSUE TITLE
Ill-formatted POSIX class not being evaluated correctly

### ISSUE THREAD

**Issue by coatless** [tidyverse/stringr#236]
The requirement of surrounding the POSIX inside of a character class `[]` is not being respected.

e.g. `[:alpha:]` A posix character class may only appear inside a character class `[]`

In `stringr`:

``` r
library("stringr")
str_detect("bdef", "[[:alpha:]]")
#> [1] TRUE
str_detect("bdef", "[:alpha:]")
#> [1] TRUE
```

The last variant should be `FALSE`, but is instead being displayed as `TRUE`. c.f. 

http://stringr.tidyverse.org/articles/regular-expressions.html#matching-multiple-characters

Consider base R variants:

``` r
grepl("[[:alpha:]]", "bdef")
#> [1] TRUE
grepl("[:alpha:]", "bdef")
#> [1] FALSE
```

**Comment by gagolews** [comment]
Isn't `[: alpha:]` like matching a single :, a, l, p, or h here?

**Comment by coatless** [comment]
@gagolews yes, that is indeed the desired behavior. Instead, it is matching any alphabet characters. A couple more examples: 

``` r
library("stringr")
str_detect("1234", "[:alpha:]")
#> [1] FALSE
str_detect(":18", "[:alpha:]")
#> [1] FALSE

grepl("[[:alpha:]]", ":18")
#> [1] FALSE
grepl("[:alpha:]", ":18")
#> [1] TRUE
```

**Comment by gagolews** [comment]
It is a documented feature of the ICU regex engine: http://userguide.icu-project.org/strings/regexp, see section *Set Expressions (Character Classes)*

**Comment by gagolews** [comment]
Also, I don't recommend relying on POSIX character classes, we live in a Unicode world now

**Comment by coatless** [comment]
@gagolews is there a compile time flag that could be set to disable this feature? The issue here is deviation from the standard regex implementation of POSIX.

**Comment by gagolews** [comment]
None that I know of.
