### ISSUE TITLE
lookaround with multiple Chinese characters

### ISSUE THREAD

**Issue by rhohz** [tidyverse/stringr#238]
Here is an example:

str <- "xyz单45.67blah23blah两个67.2blah"
pat1 <- "(?<=ah)\\d+\\.?\\d*"
pat2 <- "(?<=单)\\d+\\.?\\d*"
pat3 <- "(?<=两个)\\d+\\.?\\d*"
str_extract(str, pat1)   # 23
str_extract(str, pat2)   # 45.67
str_extract(str, pat3)   # NA

With regexpr() and regmatches(), we can get correct result.

**Comment by gagolews** [comment]
Are you using the most recent version (1.2.1) of the stringi package?

**Comment by rhohz** [comment]
Thanks.
I use version 1.1.7. When I update it to the latest version, it succeeds.
By the way, I should use double backslash in the codes above
