### ISSUE TITLE
Preserve element names during regex operations

### ISSUE THREAD

**Issue by bwiernik** [tidyverse/stringr#243]
Currently, the stringr regex functions discard element names if present.

For example:
```
char <- c(a = "abc", b = "def", c = "bcd)
stringr::str_replace_all(char, "bc", "test")
```

This means that, at best, to use the stringr regex functions with named vectors, the names have to first be saved to a different object and then be re-applied after the regex is done. At worst (e.g., for string_extract_all), it means it's basically impossible to work with named vectors using stringr.

Can these functions be adjusted to preserve element names?

**Comment by hadley** [comment]
See general issue at https://github.com/gagolews/stringi/issues/59
