### ISSUE TITLE
promise already under evaluation: recursive default argument reference or earlier problems

### ISSUE THREAD

**Issue by samhinshaw** [tidyverse/stringr#244]
I wanted to document this issue in case anyone in the future runs into it.

**Problem:**

Upon running any `stringr` function, I was greeted with the following error message: 

```
promise already under evaluation: recursive default argument reference or earlier problems
```

**Solution:**

Reinstall `stringr`

```r
remove.packages('stringr')
install.packages('stringr')
```

**Comment by yichangyu** [comment]
Hi Sam,
Thanks for posting this here, solved my issue.
