### ISSUE TITLE
For str_view, display names when length(string) > 1

### ISSUE THREAD

**Issue by bschneidr** [tidyverse/stringr#246]
The usefulness of the `str_view` functions could be improved by displaying names from vectors in the HTML created by `str_view_widget`. 

For example, suppose you want to view the results of matching a regex on the following named vector:

    words <- c("Recipe" = "Brulee", 
               "Artist" = "Goulet", 
               "Walk" = "Sashay")

    pattern <- "(ee|et|ay)"

When you call `str_view(words, pattern)`, it would be helpful to see the name of each element displayed in the viewing widget.
![image](https://user-images.githubusercontent.com/19809917/42332908-45f27dac-8047-11e8-9b87-c6c5d85b52ff.png)

Here's what one currently sees upon calling `str_view(words, pattern)`:
![image](https://user-images.githubusercontent.com/19809917/42332971-6f185706-8047-11e8-9a19-91c418a3a753.png)

The main use case I have in mind for this functionality is to quickly find spelling mistakes in plots produced by ggplot2 objects, using some combination of `str_view` and `hunspell`. Adding labels corresponding to element names would make it easy to find that, for example, a plot's title has a spelling mistake but the subtitle is ok.

    plot_labs <- myplot$labels
    str_view(plot_labs, "in ") 
![image](https://user-images.githubusercontent.com/19809917/42333207-1f8709e8-8048-11e8-9d54-1d4c59d2af85.png)

If this would be a welcome change, I'd be more than happy to submit a pull request to implement this.

**Comment by hadley** [comment]
`str_view()` is deliberately quite simple; for more complex needs I'd recommend [regexplain](https://www.garrickadenbuie.com/project/regexplain/)

**Comment by bschneidr** [comment]
Totally makes sense. Thanks for the recommendation!
