### ISSUE TITLE
unexpected behaviour str_remove_all(pattern = "[:punct:]")

### ISSUE THREAD

**Issue by juanrocha** [tidyverse/stringr#248]
When trying to remove all punctuation characters of a string, the function fails at removing all of them despite using the _all version. Here is a reproducible example:
```r
> packageVersion('stringr')
[1] ‘1.3.1’
> x <- "h<e$ll|o*(||*& w$or[l]d"
> stringr::str_remove_all(x, pattern = "[[:punct:]]")
```
which in my machine produces the following result:
```r
[1] "h<e$ll|o|| w$orld"
```
I can get the expected result with:
```r
> tm::removePunctuation(x)
[1] "hello world"
```
So I'm not sure if its a problem with `str_remove_all` or if I'm missing specifying an important option in the function.

**Comment by gagolews** [comment]
See a note on stringi's `?"stringi-search-charclass"`

**Comment by juanrocha** [comment]
Thanks for the hint, I got the expected behaviour with:
```r
> str_remove_all(x, "[[\\p{P}][\\p{S}]]")
[1] "hello world"
```
I leave the note here in case someone else ran into the same issue.
