### ISSUE TITLE
Unexpected str_replace_all behavior when doing conditional replacements using named character vector

### ISSUE THREAD

**Issue by DieselAnalytics** [tidyverse/stringr#256]
I am using str_replace_all from the stringr package along with a named character vector to do a conditional replacement. The code snippet below illustrates how I am trying to do so. 

It is working as expected most of the time except when I am trying to do a conditional replacement for "LS". In that situation it appears to be matching for "LS" and "S". Is that intended behavior or a bug? If it is intended behavior could you please explain why and what I should be doing instead? Thanks in advance!

```

library(tidyverse)
library(stringr)

Football_Players <- 
  tibble(
    Player = c("Trevon Young", "Logan Woodside", "Jordan Whitehead", "Jimmy Landes"),
    Position = c("EDGE", "QB", "S", "LS")
  )

Position_Mappings <-
  c(
    "EDGE" = "Defensive Line",
    "QB" = "Quarterback",
    "LS" = "Special Teams",
    "S" = "Defensive Back"
  )

output <-
  Football_Players %>%
  mutate(
    New_Position = str_replace_all(Position, Position_Mappings)
  )

```

**Comment by yutannihilation** [comment]
`str_replace_all()` replaces the patterns iteratively, so `"LS"` is replaced with `"Special Teams"` first, and the first character `"S"` is replaced with `"Defensive Back"`. If you change the order of `"LS"` and `"S"`, you can get the result you want.

If you want to match the pattern against the whole string, you can use `^` and `$`.

```r
Position_Mappings <-
  c(
    "^EDGE$" = "Defensive Line",
    "^QB$" = "Quarterback",
    "^LS$" = "Special Teams",
    "^S$" = "Defensive Back"
  )
```

But, in this case, I don't think you need regex :)

```r
Football_Players %>%
  mutate(
    New_Position = Position_Mappings[Position]
  )
```

**Comment by DieselAnalytics** [comment]
Thanks @yutannihilation! I did not know you could regex in the name. That's powerful. Thanks for your help!
