### ISSUE TITLE
str_[starts|ends]

### ISSUE THREAD

**Issue by hammer** [tidyverse/stringr#258]
Maybe not worth the API bloat, but I think regex-phobic users might like to have `str_starts(string, prefix)` as an alias for `str_detect(string, "^prefix")` and `str_ends(string, suffix)` as an alias for `str_detect(string, "suffix$")`.

For some evidence of need, [Does R have function startswith or endswith like python?](https://stackoverflow.com/questions/31467732/does-r-have-function-startswith-or-endswith-like-python) has quite a few upvotes.

I know we have `startsWith` and `endsWith` in base R; I just prefer to stay in the tidyverse!

**Comment by gagolews** [comment]
note stringi has `stri_endswith` and `stri_startswith`

**Comment by jonthegeek** [comment]
Claiming this issue.
