### ISSUE TITLE
Fail more gracefully when str_view() is called in the absence of htmlwidgets

### ISSUE THREAD

**Issue by jennybc** [tidyverse/stringr#263]
Although htmlwidgets is in Suggests, we don't quite follow our own best practice within `str_view()` and related helpers re: checking if it's installed. The error message is sub-optimal:

``` r
> str_view(fruit, "melon")
Error in loadNamespace(name) : there is no package called 'htmlwidgets'
```

It should be more precise about the problem and the solution.

Resources to consult:

  * Consult the [Namespaces chapter](http://r-pkgs.had.co.nz/namespace.html) of R Packages, specifically the bit about using `requireNamespace("x", quietly = TRUE)`
  * Search for "requireNamespace" on GitHub where the user is "tidyverse" or "r-lib" for examples of how it's done in other packages. Enter something like this into GitHub search: `requireNamespace user:r-lib`. Focus on the hits found in "Code".
  * Read the section of the tidyverse style guide on [error messages](http://style.tidyverse.org/error-messages.html).

*This issue was written in preparation for [Tidyverse Developer Day](https://www.tidyverse.org/articles/2018/08/tidyverse-developer-day/). Unless there's a really good reason to do otherwise, please leave it for handling then.*

**Comment by AmeliaMN** [comment]
I'm interested in trying this, although I don't fully understand the issue yet.
