### ISSUE TITLE
Add feature to str_split

### ISSUE THREAD

**Issue by giovannikraushaar** [tidyverse/stringr#264]
Dear all,

I think that add a "type" option in the function str_split , as it has been made here https://www.statworx.com/de/blog/strsplit-but-keeping-the-delimiter/ by Jakob Gepp would be a very interesting and useful feature, especially for beginners like me. Moreover you could easily leave type='remove' as default for backward compatibility.

**Comment by hadley** [comment]
I think that's a bit specialised for stringr
