### ISSUE TITLE
str_split inside of mutate takes the whole column as input instead of just the row

### ISSUE THREAD

**Issue by blablablerg** [tidyverse/stringr#265]
Hi, 

When strsplit is used inside a mutate, it uses the whole column as input instead of just the row (as expected). 
Using rowwise() is the easy fix, but that shouldn't be necessary in IMHO.

**Comment by yutannihilation** [comment]
Are you aware that `simplify = TRUE` or `str_split_fixed()` return a character matrix?

``` r
library(tidyverse)

str_split(c("a b", "c d", "e f g"), "\\s", simplify = TRUE)
#>      [,1] [,2] [,3]
#> [1,] "a"  "b"  ""  
#> [2,] "c"  "d"  ""  
#> [3,] "e"  "f"  "g"

str_split_fixed(c("a b", "c d", "e f g"), "\\s", 2)
#>      [,1] [,2] 
#> [1,] "a"  "b"  
#> [2,] "c"  "d"  
#> [3,] "e"  "f g"

d <- data.frame(x = c("a b", "c d", "e f g"), stringsAsFactors = FALSE)

d %>%
  mutate(x = str_split(x, "\\s", simplify = TRUE)[, 1])
#>   x
#> 1 a
#> 2 c
#> 3 e
```

<sup>Created on 2018-12-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bounlu** [comment]
@yutannihilation 

your solution still does not work when one wants to do rowwise operation:

data.frame(x = c("1 2", "3 4", "5 6")) %>%
mutate(x = str_split(x, "\\s", simplify = TRUE) %>% as.numeric() %>% sum())

```
 x
1 21
2 21
3 21
```

data.frame(x = c("1 2", "3 4", "5 6")) %>% rowwise() %>%
mutate(x = str_split(x, "\\s", simplify = TRUE) %>% as.numeric() %>% sum())
```
# A tibble: 3 × 1
# Rowwise: 
      x
  <dbl>
1     3
2     7
3    11
```

**Comment by yutannihilation** [comment]
Sorry, I think I don't understand your point. If you want to `rowwise()`, stringr now provides `str_split_1()`.

https://www.tidyverse.org/blog/2022/12/stringr-1-5-0/#splitting

**Comment by bounlu** [comment]
Yes, I agree you don't understand my point.

Please copy paste my code into RStudio and try to rerun it, with and without `rowwise()` as well as with different forms of `str_split*`.

**Comment by werkstattcodes** [comment]
Hello, 
AFAIKT, `str_split `works as intended, I think you're simply missing that it returns a list and hence requires `map `if you want to manipulate the results. Let's keep the conversation respectful. 


``` r
library(tidyverse)

data.frame(x = c("1 2", "3 4", "5 6")) %>%
  mutate(x=str_split(x, "\\s")) 
#>      x
#> 1 1, 2
#> 2 3, 4
#> 3 5, 6

data.frame(x = c("1 2", "3 4", "5 6")) %>%
  mutate(x=str_split(x, "\\s") %>%  map(., as.numeric) %>% map_dbl(., sum))
#>    x
#> 1  3
#> 2  7
#> 3 11
```

<sup>Created on 2023-03-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by bounlu** [comment]
Sorry if you felt uncomfortable with my answer.

No, `str_split` does not return a list as long as you provide `simplify = TRUE` parameter, like in my examples.

I think the original request was to avoid additional functions to manipulate the `str_split` output, hence to make it compatible with the other functions in the `tidyverse` using the `%>%` notation, which is the expected behaviour. Otherwise there are many alternative ways to get the desired result, like `rowwise()` which was suggested at the first place.
