### ISSUE TITLE
Vignette comparing stringr to base R

### ISSUE THREAD

**Issue by hadley** [tidyverse/stringr#266]
Starting with a table lets you easily find the stringr function equivalent to a base R function (and vice versa)

**Comment by moodymudskipper** [comment]
Great idea, it's also not always clear why an equivalent exists or how it differs from a *`stringi`* close equivalent, I often found myself wondering:

* Is it just a matter of reordering the parameters ?
* Is it faster ?
* Does it address differently corner cases ?

Usually the doc of stringr and stringi contain the answer but it takes time to dig it out.

I did some work on SO here in case it helps :

[Difference between `paste`, `str_c`, `str_join`, `stri_join`, `stri_c`, `stri_paste`?](https://stackoverflow.com/questions/53118271/difference-between-paste-str-c-str-join-stri-join-stri-c-stri-pa/53118273#53118273)

And I also had posted comparisons with base functions in the examples off rdocumentation.com : 

[str_detect](https://www.rdocumentation.org/packages/stringr/versions/1.3.1/topics/str_detect)
[str_length](https://www.rdocumentation.org/packages/stringr/versions/1.3.1/topics/str_length)

**Comment by hadley** [comment]
I don't think a comparison with stringi would be terribly useful as the functions are very close.
