### ISSUE TITLE
Consider using GPL (>=2), not GPL-2

### ISSUE THREAD

**Issue by yutannihilation** [tidyverse/stringr#269]
Is it possible to use `GPL (>=2)`, not `GPL-2`? IIUC, `GPL-2` probably means "GPLv2 only", unless otherwise declared that you permit "or later." This might conflict with GPLv3 from a strict viewpoint.

(I'm really hesitant to file this kind of issues, but I'm stuck with this license concern to convince my company to publish my stringr-dependent R package as an OSS...)

**Comment by hadley** [comment]
To make this change, we need to get approval from all copyright holders, which is basically anyone who has made a non-trivial contribution. If you figure out that list (probably using https://github.com/tidyverse/stringr/graphs/contributors), we can use this github issue to get everyone to confirm that they're happy with it (I don't have any problems with making the change).

**Comment by gagolews** [comment]
GPL>=2 is fine with me

**Comment by yutannihilation** [comment]
Thanks, I will try, though it seems very difficult.

(For my personal problem, I decided to use stringi instead of stringr, so I'm OK now)

**Comment by hadley** [comment]
Ok, I'll close for now. I don't think it's quite as hard as you think though, so let me know if you ever need to try again.

**Comment by yutannihilation** [comment]
Sorry, I lost my passion this time... Thanks.

**Comment by zapashcanon** [comment]
@hadley come on, everyone was OK about it in #137...

**Comment by hadley** [comment]
@zapashcanon trying to re-license someone else's package in this way is extremely aggressive. We are moving all tidyverse/r-lib to MIT (where possible), and stringr will handed in due course.
