### ISSUE TITLE
Add str_between

### ISSUE THREAD

**Issue by diegogarcilazo** [tidyverse/stringr#274]
On more than one occasion I find myself using ranges between characters and I try to use the dplyr :: between function but it works only with numerical vectors. I also need to exclude some text value from the range. This function has helped me to make coherent with dplyr :: between.

```R
#' Do values in a string vector fall in specified range?
#' str_between is case insensitive by default.
#' @param x	 A string vector of values.
#' @param left,right Boundary values.
#' @param exclude vector string exclude values inside range.

str_between <- function(x, left, right, exclude = NULL){
  
  x <- toupper(x)
  
  (x >= toupper(left) & x <= toupper(right)) & !x%in%toupper(exclude)
  
}


example 

letts <- letters[1:20]

mask <- str_between(letts, "b", "E", exclude = "c")

letts[mask]

```

**Comment by hadley** [comment]
I think this is quite perilous because it depends on the locale, and there are critical difference in lexicographic order between locals (particularly around case)

**Comment by diegogarcilazo** [comment]
Maybe it's better to use regular expressions with str_detect().
