### ISSUE TITLE
possible str_c imprecision

### ISSUE THREAD

**Issue by yj-danielyang** [tidyverse/stringr#275]
Not sure if this is a str_c bug or a R bug in general, but here we go:

> a <- 10
> b <- 10.02
> c <- a-b
> c
[1] -0.02
> str_c(c)
[1] "-0.0199999999999996"
> str_c(a-b)
[1] "-0.0199999999999996"

**Comment by gagolews** [comment]
That's a pretty standard behavior of the FP arithmetic, see https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html.

If you want fancy formatting (e.g., with rounding), use,  e.g., `format()`

```
> a <- 10
> b <- 10.02
> c <- a-b
> c
[1] -0.02
> as.character(c)
[1] "-0.0199999999999996"
> format(c)
[1] "-0.02"

```

**Comment by hadley** [comment]
Thanks @gagolews!
