### ISSUE TITLE
str_split_n(string, pattern, n)

### ISSUE THREAD

**Issue by hadley** [tidyverse/stringr#278]
Returns a character vector.

For the moderately common case where you only want to extract a single piece from a string.

Inspired by `SPLIT_PART()` from SQL.

**Comment by jhrcook** [comment]
Is this issue supposed to still be open? It looks like commit 4537228 addressed it. If not, let me know and I can try to help out.

**Comment by noderboarder** [comment]
I cannot use the function, and it tells that could not find function "str_split_n" on console.
Is that deprecated?!
