### ISSUE TITLE
Implement str_like()

### ISSUE THREAD

**Issue by hadley** [tidyverse/stringr#280]
Which follows the SQL `LIKE` definition

**Comment by quartin** [comment]
I have been thinking a little bit about this, and though about the following implementation plan:

* Add a [`like` modifier](https://github.com/tidyverse/stringr/blob/master/R/modifiers.r) - `str_like` default pattern type would be it;
* Have a conversion method from SQL like-clauses to regex and so, under the hood, `str_like` would use `stringr::str_subset`

Problems I see here: 
* That second point being way harder than what I am imagining, lot's of hammering of edge cases in the conversion;
* Possibility to generate an invalid regex and user sees a confusing error message (_but i'm not using regex!_).

Is this anything like what you would expect of this feature?

**Comment by hadley** [comment]
* I was thinking a bit simpler than that — I was imagining just an equivalent of `str_detect()`. 

* Yes, I was thinking of using regular expressions to convert like syntax to another regular expression; I _think_ the syntax is simple enough that it's unlikely to cause too many problems.

**Comment by rjpat** [comment]
Created a PR for this #315 , open to any adjustments
