### ISSUE TITLE
str_c docmentation when collapse is non-NULL

### ISSUE THREAD

**Issue by BenjaminLouis** [tidyverse/stringr#281]
Be careful : this is an issue about a tiny detail!
In the value section, the documentation of `str_c` says : _If collapse is non-NULL, a character vector of length 1._

This is true until the input vectors is of length 0 (as a result of a `setdiff` for example) as shown by the reprex above

```
stringr::str_c(character(0), collapse = ";")
#> character(0)
``` 

Maybe the documentation should be updated ? I suggest : 
the mysterious update : _If collapse is non-NULL, a character vector of length 0 or 1._
the transparent update: _If collapse is non-NULL, a character vector of length 1 or 0 if the input vector is of length 0 itself._

**Comment by hadley** [comment]
I think this is a bug, not a problem with the documentation.

**Comment by hadley** [comment]
Filed upstream in https://github.com/gagolews/stringi/issues/369
