### ISSUE TITLE
options attribute on str_detect pattern string causes error in stri_detect_regex

### ISSUE THREAD

**Issue by misea** [tidyverse/stringr#287]
If one happens to have a stray options attribute on a string used as a pattern, str_detect blows up somewhat ungracefully:

```r
p <- "fun"
attr(p, "options") <- 123
str_detect("funny", p)
```

```
Error in stri_detect_regex(string, pattern, opts_regex = opts(pattern)) : 
  argument `opts_regex` should be a list
```

To a newbie it's not 100% clear that opts(pattern) means attr(pattern, "options"), but it's particularly vexing if the options attribute happens to be set on the pattern string by some unrelated code.

**Comment by hadley** [comment]
I think this is out of scope for stringr; if you create an invalid object, you're on your own.
