### ISSUE TITLE
str_detect() raises an error when using regex (regex options must be a list)

### ISSUE THREAD

**Issue by bonmac** [tidyverse/stringr#288]
Function `str_detect` raises an error.

``` r
library(stringr)
#> Warning: package 'stringr' was built under R version 3.5.2

fruit <- c("apple", "banana", "pear", "pinapple")
str_detect(fruit, "^a")
#> Error in stri_detect_regex(string, pattern, negate = negate, opts_regex = opts(pattern)): argument `opts_regex` should be a list
```

<sup>Created on 2019-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

My session info is as follows

``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.0 (2018-04-23)
#>  os       Windows >= 8 x64            
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Africa/Nairobi              
#>  date     2019-02-28                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.0   2017-04-11 [1] CRAN (R 3.5.0)
#>  backports     1.1.3   2018-12-14 [1] CRAN (R 3.5.2)
#>  callr         3.1.1   2018-12-21 [1] CRAN (R 3.5.2)
#>  cli           1.0.1   2018-09-25 [1] CRAN (R 3.5.1)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.1)
#>  devtools      2.0.1   2018-10-26 [1] CRAN (R 3.5.1)
#>  digest        0.6.18  2018-10-10 [1] CRAN (R 3.5.1)
#>  evaluate      0.13    2019-02-12 [1] CRAN (R 3.5.0)
#>  fs            1.2.6   2018-08-23 [1] CRAN (R 3.5.1)
#>  glue          1.3.0   2018-07-17 [1] CRAN (R 3.5.1)
#>  highr         0.7     2018-06-09 [1] CRAN (R 3.5.0)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.0)
#>  knitr         1.21    2018-12-10 [1] CRAN (R 3.5.2)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.0)
#>  pkgbuild      1.0.2   2018-10-16 [1] CRAN (R 3.5.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.1)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.0)
#>  processx      3.2.1   2018-12-05 [1] CRAN (R 3.5.1)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.2)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.2)
#>  Rcpp          1.0.0   2018-11-07 [1] CRAN (R 3.5.1)
#>  remotes       2.0.2   2018-10-30 [1] CRAN (R 3.5.1)
#>  rlang         0.3.1   2019-01-08 [1] CRAN (R 3.5.2)
#>  rmarkdown     1.11    2018-12-08 [1] CRAN (R 3.5.0)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.1)
#>  stringi       1.3.1   2019-02-13 [1] CRAN (R 3.5.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#>  testthat      2.0.1   2018-10-13 [1] CRAN (R 3.5.1)
#>  usethis       1.4.0   2018-08-14 [1] CRAN (R 3.5.1)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.0)
#>  xfun          0.5     2019-02-20 [1] CRAN (R 3.5.0)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.0)
#> 
#> [1] C:/bmakone/r-libs
#> [2] C:/Program Files/R/R-3.5.0/library
```

<sup>Created on 2019-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by cderv** [comment]
This is working for me with the same version of 📦 
``` r
fruit <- c("apple", "banana", "pear", "pinapple")
stringr::str_detect(fruit, "^a")
#> [1]  TRUE FALSE FALSE FALSE
sessioninfo::package_info("stringr")
#>  package  * version date       lib source        
#>  glue       1.3.0   2018-07-17 [1] CRAN (R 3.5.1)
#>  magrittr   1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  stringi    1.3.1   2019-02-13 [1] CRAN (R 3.5.2)
#>  stringr    1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#> 
#> [1] C:/Users/chris/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.1/library
```

<sup>Created on 2019-02-28 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I am with R 3.5.1 though... 🤔

**Comment by turgeonmaxime** [comment]
For what it's worth, I get the same error as @bonmac but with a different version of `R` and of `stringi`:

``` r
sessioninfo::package_info("stringr")
#>  package  * version date       lib source        
#>  glue       1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  magrittr   1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  stringi    1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr    1.4.0   2019-02-10 [1] CRAN (R 3.5.3)
#> 
#> [1] C:/Users/TURGEONMA/Documents/Rlibs
#> [2] C:/Program Files/R/R-3.5.3/library
```

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by cderv** [comment]
With the same versions, still no error. 
``` r
fruit <- c("apple", "banana", "pear", "pinapple")
stringr::str_detect(fruit, "^a")
#> [1]  TRUE FALSE FALSE FALSE
sessioninfo::package_info("stringr")
#>  package  * version date       lib source        
#>  glue       1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  magrittr   1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  stringi    1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr    1.4.0   2019-02-10 [1] CRAN (R 3.5.3)
#> 
#> [1] C:/Users/chris/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.3/library
```

<sup>Created on 2019-03-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Did you try to reinstall stringr and stringi ?

**Comment by turgeonmaxime** [comment]
I can confirm that after reinstalling both `stringi` and `stringr` (in that order), everything works fine

``` r
fruit <- c("apple", "banana", "pear", "pinapple")
stringr::str_detect(fruit, "^a")
#> [1]  TRUE FALSE FALSE FALSE
sessioninfo::package_info("stringr")
#>  package  * version date       lib source        
#>  glue       1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  magrittr   1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  stringi    1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr    1.4.0   2019-02-10 [1] CRAN (R 3.5.3)
#> 
#> [1] C:/Users/TURGEONMA/Documents/Rlibs
#> [2] C:/Program Files/R/R-3.5.3/library
```

<sup>Created on 2019-03-15 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bonmac** [comment]
I also confirm that the error goes away after updating tidyverse

**Comment by Ludsfer** [comment]
Good morning.
Please I am having this error while running this code. can anyone help me?
Please I need your help as earlier as possible it is for a paper

library(BatchGetSymbols)                    OK


> AAPL <- BatchGetSymbols("AAPL", first.date = "2005-01-01", last.date = "2009-12-31", do.cache = FALSE)

Running BatchGetSymbols for:
   tickers =AAPL
   Downloading data for benchmark ticker
^GSPC | yahoo (1|1)
AAPL | yahoo (1|1) - Got 100% of valid prices | Feels good!Error in stri_detect_regex(string, pattern, negate = negate, opts_regex = opts(pattern)) : 
  Unrecognized backslash escape sequence in pattern. (U_REGEX_BAD_ESCAPE_SEQUENCE, context=`C:\Users\josep\AppData\Local\Temp\RtmpwVMbgS`)
> sessioninfo::package_info("stringr")
 package  * version date       lib source        
 glue       1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 magrittr   2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
 stringi    1.5.3   2020-09-09 [1] CRAN (R 4.0.3)
 stringr    1.4.0   2019-02-10 [1] CRAN (R 4.0.3)

[1] C:/Users/josep/Documents/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.3/library



I have tried those solutions provided above (reinstall "tidyverse",  uninstall and reinstall both "stringi" and "stringr" in this order, ... and so on)

**Comment by cderv** [comment]
When you have those types of issues, you should look first and ask in repo of the package of the function you are directly using. Here it is clearly something related to `BatchGetSymbols` which uses `stringr`and not an issue with `stringr` package directly. 

It seems the issue you have has already been fixed there. See 
https://github.com/msperlin/BatchGetSymbols/issues/21

Hope it helps.

**Comment by Ludsfer** [comment]
Thank you very much @cderv. I just got an update of a new version of the package and now everything works perfectly.
Thank for your coment

**Comment by Gautamshahi** [comment]
Yes, reinstalling package stringi and stringr solves the issue. The issue arises only in windows but in mac it works well. I hope it will help others.
