### ISSUE TITLE
Implement extract() and extract2() approaches from tidyr

### ISSUE THREAD

**Issue by hadley** [tidyverse/stringr#291]
Return data frames

https://github.com/tidyverse/tidyr/issues/548

**Comment by flying-sheep** [comment]
Important consideration for extract2: Consider that named groups may be optional or lie inside optional groups.

```r
tbl <- tibble(a = c('ab_cd', 'abd', 'a_cd', 'ad'))
extract <- extract2(tbl, 'a(?<B>b)?(?:_(?<C>c))?d')
extract$B == c('b', 'b', NA, NA)
extract$C == c('c', 'NA', 'c', NA)
```

**Comment by flying-sheep** [comment]
Another point is how to deal with `.match`: In the presence of optional groups it contains information that can’t be derived. Maybe we should add a `no_match` parameter:

```r
mismatch <- is.na(l$.match)
if (is.character(match)) {
    l[[match]] <- !mismatch
} else if (isTRUE(match) && any(mismatch)) {
  stop(
    'Mismatch(es) starting from row ',
    which(mismatch)[[1]],
    '. Specify `match!=TRUE` to handle mismatches'
  )
}
```

**Comment by hadley** [comment]
stringr can't support named captured groups until #71 happens, so it would require on explicit names to begin with. We could, however, consider an [nc](https://github.com/tdhock/nc) inspired syntax like `str_extract(x, c(type = ".*", "|", fruit = "orange|apple"))`

**Comment by hadley** [comment]
Something like this:

```R
str_match_df <- function(x, pattern) {
  grouped <- paste0("(", pattern, ")", collapse = "")
  named <- names2(pattern) != ""
  matches <- str_match(x, grouped)

  out <- as.data.frame(matches[, c(FALSE, named), drop = FALSE])
  names(out) <- names(pattern)[named]
  out
}
```

**Comment by hadley** [comment]
It's unfortunate that `tidyr::extract()` aligns with `stringr::str_match()`.

**Comment by hadley** [comment]
Superseded by bigger design in https://github.com/tidyverse/tidyups/pull/15
