### ISSUE TITLE
request: str_dice() to split string in equal-length chunks

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/stringr#292]
Imagine I have a string

```r
s <- "abcdefghi"
```
and want it to be split in substrings of equal length 3 (regex is ineffective for this):

```r
s_dice <- str_dice(s,width=3)
#> [[1]]
#> [1] "abc" "def" "ghi"
```
note str_dice() returns a list, since its input can be a vector of strings (in the manner of str_split).

currently, one needs to write:
```r
str_dice <- function(s,width) { # does not return list
   L <- str_length(s)
   str_sub(s, from=seq(1L,L-width+1,width), to=seq(width,L,width))
}
```

**Comment by hadley** [comment]
This feels sufficiently special purpose that it's out of scope for stringr, sorry.

**Comment by jrausch12** [comment]
@hadley I would argue it is in scope. For instance, a use case can be combining a raw vector into a single string for db storage, then extracting it and wanting to re-create the raw vector.
