### ISSUE TITLE
[New Function] str_unique() -- wrapper around stri_unique()

### ISSUE THREAD

**Issue by seasmith** [tidyverse/stringr#294]
`str_unique()` would bring behavior not present in `base::unique()` -- notably testing for canonical similarity between strings (ie `n` vs. `ñ`) and case sensitivity (ie `n` vs. `N`).

Both of these behaviors are controlled by the `strength` argument passed on to the `opts_collator` argument in `stringi::stri_unique()`.

```r
library(stringi)

# As implemented at https://github.com/seasmith/stringr/tree/str_unique
str_unique <- function(string, ...) {
  stri_unique(string, opts_collator = stri_opts_collator(...))
}

str_unique(c("\u00dc", "\u00fc", "U", "u"), strength = 3)
#> [1] "Ü" "ü" "U" "u"
str_unique(c("\u00dc", "\u00fc", "U", "u"), strength = 2)
#> [1] "Ü" "U"
str_unique(c("\u00dc", "\u00fc", "U", "u"), strength = 1)
#> [1] "Ü"
```

My branch includes tests and passes all Travis-CI checks except R 3.1.

**Comment by hadley** [comment]
Seems like a reasonable complement to `str_sort()` and `str_order()`. Do you want to do a PR?

**Comment by seasmith** [comment]
Opened PR #314.
