### ISSUE TITLE
str_replace_all doesn't act same as str_replace when it comes to UTF-8

### ISSUE THREAD

**Issue by Marcade80** [tidyverse/stringr#295]
I am trying to use a named vector to replace Chinese (UTF-8) strings. It works fine if I use str-replace to replace word by word; but for convenience i'd like to use a named vector. Which seems to work with str_replace_all if I use Latin1 encoded strings. It does not seem to work with UTF-8 encoded strings.

---

Working:
str_replace('blah 采集月份 blah 序号 blah', "采集月份", "Month")

Not working:
str_replace_all('blah 采集月份 blah 序号 blah', c("采集月份"="Month", "序号"="No"))

**Comment by cderv** [comment]
FWIW, this is working if I build the vector of replacement before assigning names
```r
> replace_vec <- setNames(c("Month", "No"), c("采集月份", "序号"))
> replace_vec
采集月份     序号 
 "Month"     "No" 
> stringr::str_replace_all('blah 采集月份 blah 序号 blah', replace_vec)
[1] "blah Month blah No blah"
```

Something to do with how names are stored when in special encoding... 🤔 
```r
> names(replace_vec) == names(c("采集月份"="Month", "序号"="No"))
[1] FALSE FALSE
> > names(replace_vec)
[1] "采集月份" "序号"    
> names(c("采集月份"="Month", "序号"="No"))
[1] "<U+91C7><U+96C6><U+6708><U+4EFD>" "<U+5E8F><U+53F7>"        
```

So it may be an issue with R vector type, its name and UTF8 encoding.

**Comment by Marcade80** [comment]
Thanks for helping out! Yeah I realized as well that apparently it doesn't appreciate the vector names being UTF-8 (Chinese). Though values seem to be no problem. :-/

**Comment by hadley** [comment]
Yeah, this is an underlying issue with R — when you create names using a call to `c()`, the names are converted to symbols, which are always encoded in the native encoding (which on windows will not be UTF-8). Unfortunately I don't think there's anything stringr can do about this.
