### ISSUE TITLE
documentation linking issue on str_squish

### ISSUE THREAD

**Issue by neonira** [tidyverse/stringr#300]
In a manual page (.Rd), if you link to _**str_squish**_, using **_\code{\link[stringr]{str_squish}}_**, package compiler complains with following message 

> Rd warning: C:/aubay_workspace/mySoftware/r-packages/wyz.string.ops/man/normalizeSpaces.Rd:27: file link 'str_squish' in package 'stringr' does not exist and so has been treated as a topic

If you link to _**str_trim**_, no such issue appears. 

I still guess why ?

**Comment by hadley** [comment]
It's because technically you are supposed to link to topics, not function names. But in practice this causes few problems so you can safely ignore the warning.
