### ISSUE TITLE
no_match argument for str_match() and str_extract()

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/stringr#306]
If the pattern doesn't match the string then `str_extract()` and `str_match()` simply return NA resp. a row of NA. It would be nice if one could control this behaviour via an extra argument, e.g. `no_match` that could be one `"error"`, `"warning"` or `"na"` (the current default).

**Comment by hadley** [comment]
Unfortunately, I don't think that would be consistent with the way stringr generally deals with `NA`s.
