### ISSUE TITLE
`str_detect()` output not equivalent to `grepl()`

### ISSUE THREAD

**Issue by balthasars** [tidyverse/stringr#309]
According to the `str_detect()` help page, `grepl()` and `str_detect()` are equivalent — in this case, however, they do not return the same output (also not with the underlying `stringi::stri_detect_fixed()`):

``` r
vector <- c("private Reise", NA, NA)
stringr::str_detect(vector, "privat")
#> [1] TRUE   NA   NA
grepl("privat", vector)
#> [1]  TRUE FALSE FALSE
stringi::stri_detect_fixed(vector, "privat")
#> [1] TRUE   NA   NA
```

<sup>Created on 2019-09-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is this behavior intended?

**Comment by hadley** [comment]
Equivalent doesn't mean exactly equal, and I think `NA` is the correct result here.
