### ISSUE TITLE
would it possible for function in stringr to treat matrix as vector

### ISSUE THREAD

**Issue by mikeaalv** [tidyverse/stringr#311]
I know it is possible to convert matrix into vector and back into matrix or using apply type of function. 

However, it seems more reasonable and helpful if the function in stringr (such as str_replace_all) can treat array (matrix or higher dimension) as a vector itself. That is, is it possible for function in stringr to maintain dimension of the input in the output?

Thank you.

Best.
Yue

---

Example code

```r
mat=matrix("CA",nrow=10,ncol=10)
matr=str_replace(string=mat,pattern="^C",replacement="D")
```

**Comment by hadley** [comment]
It would be a lot of work, and it's easy to work around currently:

``` r
m <- matrix("CA", nrow = 5, ncol = 5)
m[] <- stringr::str_replace(m, pattern = "^C", replacement = "D")
m
#>      [,1] [,2] [,3] [,4] [,5]
#> [1,] "DA" "DA" "DA" "DA" "DA"
#> [2,] "DA" "DA" "DA" "DA" "DA"
#> [3,] "DA" "DA" "DA" "DA" "DA"
#> [4,] "DA" "DA" "DA" "DA" "DA"
#> [5,] "DA" "DA" "DA" "DA" "DA"
```

<sup>Created on 2019-10-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mikeaalv** [comment]
thank you very much. It perfectly solved my problem.
