### ISSUE TITLE
A pattern feature for str_sort and str_order?

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/stringr#312]
It's just an idea. Let's see an example:
```
> stringr::str_sort(c("a_1","a_2","b_1","b_2"))
[1] "a_1" "a_2" "b_1" "b_2"
> stringr::str_sort(c("a_1","a_2","b_1","b_2"), numeric = T)
[1] "a_1" "a_2" "b_1" "b_2"
```
But I may expect from the last instruction the output ` "a_1" "b_1" "a_2" "b_2"`.
Well, maybe not, but if I had a `pattern` option to do
```
stringr::str_sort(c("a_1","a_2","b_1","b_2"), numeric = T, pattern = "_[0-9]")
```
which would sort by the substrings captured by the pattern and I would get my expected output.

Would be such an option possible? I raise it since meanwhile, it is a bit cumbersome to produce such an output, at least in certain situations.

I've already [proposed ](https://github.com/gagolews/stringi/issues/358)it for the package `stringi`, but it seems it is not the suitable place, since it "is supposed to be a little bit lower-level." I wonder if for `stringr` is a possible feature.

Thank you for the package.

**Comment by hadley** [comment]
This feels a bit too specialised for stringr, sorry.
