### ISSUE TITLE
Add a way to access capturing groups when the `str_replace` replacement is a callback

### ISSUE THREAD

**Issue by Kodiologist** [tidyverse/stringr#316]
In Perl's `s///e` and Python's `re.replace`, the function called to replace each match can access not just the full text of the match but also the contents of capturing groups. This doesn't seem to be possible in `stringr`. Currently, a `replacement` callback can't even use backreferences in the return value, which would be a weaker feature sort of like this.

**Comment by moodymudskipper** [comment]
What about the following syntax ? If replacement is a function (or formula to be converted to a function), the matched values groups could be forwarded to the dots, and the analogy between `..1` and `\1` is intuitive. 

``` r
str_replace2 <- function(string, pattern, replacement){
  if(inherits(replacement, "formula"))
    replacement <- rlang::as_function(replacement)
  if(is.function(replacement)){
    grps <- stringr::str_match(string, pattern)[,-1]
    
    replacement <- rlang::exec(replacement, !!! lapply(seq_len(ncol(grps)), function(i) grps[,i]))
  }
  stringr::str_replace(string, pattern, replacement)
}

str_replace2(
  c("x1y", "aa2bb"), 
  "(\\D+)(\\d)(\\D+)", 
  ~paste(toupper(..1), ..3))
#> [1] "X y"   "AA bb"
```

<sup>Created on 2020-01-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
