### ISSUE TITLE
Special operator for string in string

### ISSUE THREAD

**Issue by geotheory** [tidyverse/stringr#318]
I seem to spend a disproportionate time combining `str_detect` with `dplyr::filter`, e.g:

    starwars %>% filter(str_detect(name, fixed('sky', ignore_case = TRUE)))

It feels like there's a space crying out for a special operator in stringr to enable a simpler Python-like shorthand such as:

    starwars %>% filter('sky' %IN% name)

For a simple flexible approach this might do the job:

    `%IN%` <- function(q, str) str_detect(str, regex(q, ignore_case = TRUE))
    
    starwars %>% filter('sky' %IN% name) %>% .[['name']]
    #> [1] "Luke Skywalker"   "Anakin Skywalker" "Shmi Skywalker"

Any views?

**Comment by hadley** [comment]
I'd prefer not to add operators to stringr due to the challenges of resolving namespace clashes when they occur. I think custom operators like this are best defined in your scripts.
