### ISSUE TITLE
Encoding issues with stringr and UTF-8

### ISSUE THREAD

**Issue by adisarid** [tidyverse/stringr#319]
Hi,
I'm not sure if this is a `stringr` issue, a `stringi` issue, an RStudio IDE issue or an OS issue. I do know that in the past things worked fine, and in one of the recent `stringr` updates got things messed up.

### Description

When using utf-8 text (e.g., Hebrew), the stringr functions yield unexpected results, which look like the wrong encoding. In the past everything worked fine, this started in a recent package update.

### Reprex

```
Sys.setlocale(locale = "Hebrew")
#> [1] "LC_COLLATE=Hebrew_Israel.1255;LC_CTYPE=Hebrew_Israel.1255;LC_MONETARY=Hebrew_Israel.1255;LC_NUMERIC=C;LC_TIME=Hebrew_Israel.1255"

text <- "אני אוהב לישון"
find <- "לישון"
replacement <- "לשחות"

# This yields text which is unreadable, and in the wrong encoding:
stringr::str_replace(text,
                     find,
                     replacement)
#> [1] "<U+FFFD><U+FFFD><U+FFFD> <U+FFFD><U+FFFD><U+FFFD><U+FFFD> <U+FFFD><U+FFFD><U+FFFD><U+FFFD><U+FFFD>"
```
### Workaround

Using `iconv()` (or `utf8::as_utf8()`) seems to solve the issue. For example:

```
# This works fine
stringr::str_replace(iconv(text, to = "UTF-8"),
                     iconv(find, to = "UTF-8"),
                     iconv(replacement, to = "UTF-8"))
#> [1] "אני אוהב לשחות"

# This also works fine (using as_utf8())
stringr::str_replace(utf8::as_utf8(text),
                     iconv(find, to = "UTF-8"),
                     iconv(replacement, to = "UTF-8"))
#> [1] "אני אוהב לשחות"
```

### System
   
```
R version 3.6.0 (2019-04-26)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17763)

Matrix products: default

locale:
[1] LC_COLLATE=Hebrew_Israel.1255  LC_CTYPE=Hebrew_Israel.1255    LC_MONETARY=Hebrew_Israel.1255 LC_NUMERIC=C                  
[5] LC_TIME=Hebrew_Israel.1255    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.0 magrittr_1.5   tools_3.6.0    utf8_1.1.4     stringi_1.4.3  stringr_1.4.0 
```

**Comment by gagolews** [comment]
You set your system encoding to WIndows-1255, hence all strings without marked encoding are interpreted as such

Try without `Sys.setlocale(locale = "Hebrew")`

**Comment by adisarid** [comment]
@gagolews Hmm.. Yes, that seems to be the issue. 

It does work if I omit the `Sys.setlocale` so I'm going to **thank you** and close this issue 👏, however...

I had good reasons for using `Sys.Setlocale(locale="Hebrew")` for other encoding purposes: related to how the RStudio interface renders Hebrew text. Without the `locale = "Hebrew"` the interface shows the unicode code instead of Hebrew characters (e.g. in the Environment tab or when using `View`).

This seems to be two distinct issues. Any idea about resolving both?

**Comment by gagolews** [comment]
My best shot is `Hebrew_Israel.UTF-8` or `Hebrew_Israel.UTF8` ?

**Comment by adisarid** [comment]
Thanks, @gagolews you're the best!, but no luck on windows 😢 
I tried various variations... Can you think of any windows documentation that I can read to try and figure out the "perfect locale"?

```
Sys.setlocale(locale = "Hebrew_Israel.UTF-8")
#> Warning in Sys.setlocale(locale = "Hebrew_Israel.UTF-8"): OS reports
#> request to set locale to "Hebrew_Israel.UTF-8" cannot be honored
#> [1] ""
Sys.setlocale(locale = "Hebrew_Israel.UTF8")
#> Warning in Sys.setlocale(locale = "Hebrew_Israel.UTF8"): OS reports request
#> to set locale to "Hebrew_Israel.UTF8" cannot be honored
#> [1] ""
Sys.setlocale(locale = "Hebrew_Israel.utf8")
#> Warning in Sys.setlocale(locale = "Hebrew_Israel.utf8"): OS reports request
#> to set locale to "Hebrew_Israel.utf8" cannot be honored
#> [1] ""
Sys.setlocale(locale = "Hebrew_Israel.utf-8")
#> Warning in Sys.setlocale(locale = "Hebrew_Israel.utf-8"): OS reports
#> request to set locale to "Hebrew_Israel.utf-8" cannot be honored
#> [1] ""
Sys.setlocale(locale = "Hebrew.utf8")
#> Warning in Sys.setlocale(locale = "Hebrew.utf8"): OS reports request to set
#> locale to "Hebrew.utf8" cannot be honored
#> [1] ""
Sys.setlocale(locale = "Hebrew.utf-8")
#> Warning in Sys.setlocale(locale = "Hebrew.utf-8"): OS reports request to
#> set locale to "Hebrew.utf-8" cannot be honored
#> [1] ""
```

**Comment by adisarid** [comment]
Update: after some trial and error (and manually modifying the language settings in Windows' control panel), It might be that

```
Sys.setlocale(locale = "English_Israel.65001")
```

Works partly. But still trying to figure that out...
