### ISSUE TITLE
str_to_title() does not preserve ALL CAPS

### ISSUE THREAD

**Issue by jashapiro** [tidyverse/stringr#330]
`stringr::str_to_title()` does not preserve all-caps words in that form. While this may be desirable in some cases (where all text is caps, for example), there are many cases where all caps signifies an abbreviation and the case should be preserved. Presumably the best solution to this is to make preserving all caps words an additional option, but that option is not available in `stringi::stri_trans_totitle()`, so would need to be added by another method. 
```r
test_string = "Study of CNS tumors" 
stringr::str_to_title(test_string)
#> [1] "Study Of Cns Tumors"
tools::toTitleCase(test_string)
#> [1] "Study of CNS Tumors"
```

Note that the `tools::toTitleCase` function does preserve all caps words, though its behavior is odd/inconsistent in the case where all words are all caps.

```r
caps_string = "STUDY OF CNS TUMORS"
> tools::toTitleCase(caps_string)
#> [1] "STUDY of CNS TUMORS"
> stringr::str_to_title(caps_string)
#> [1] "Study Of Cns Tumors"
```

As I write this I noticed that `stringr::str_to_title()` also does not handle "short" words like "of" as expected in standard title case (so far as that is ever defined).

**Comment by hadley** [comment]
This is out of scope for `str_to_title()`, sorry.
