### ISSUE TITLE
unused arguments not triggering error in regex

### ISSUE THREAD

**Issue by Tal1987** [tidyverse/stringr#332]
Hello, 

When using the regex function, it does not appear to give an error when I have unused arguments. 

For example below I have an unused argument (sugar muffin = "ok"), and the output was just TRUE without any error message. Thanks in advance for looking into this. 

Tal 

``` r

library(reprex)
#> Warning: package 'reprex' was built under R version 3.5.3
library(stringr) ;str_detect(string = "a", regex(pattern = "a", sugar_muffin = "ok"))
#> Warning: package 'stringr' was built under R version 3.5.1
#> [1] TRUE
```

<sup>Created on 2020-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

---

**Comment by cderv** [comment]
Hi, 

This behavior is currently expected I think. `stringr::regex` has `...` to get any options passed to `stringi::stri_opts_regex` where the documentation explicitly says 
> ... | any other arguments to this function are purposely ignored

this type of behavior is quite common with functions that takes `dots`. 
There is a new maturing 📦 ellipsis (https://ellipsis.r-lib.org/) that could help, but that would require I guess to be implemented on stringi side... 

Hope it helps understand the current behavior.

**Comment by Tal1987** [comment]
Ah I see! Newbee misunderstanding. Thanks for getting back to me and the comprehensive reply.

Have a good day, 

Tal
