### ISSUE TITLE
upper case on articles in the middle of a sentence of str_to_title() function

### ISSUE THREAD

**Issue by avila** [tidyverse/stringr#333]
### Description 
small issue but couldn't find a solution or reasoning here or on `stringi` issues. 

basically I expected ```str_to_title("saint vincent and the grenadines", locale = "en")``` to return
 ```"Saint Vincent and the Grenadines"``` and not with capitalized articles, as it returns  ```"Saint Vincent And The Grenadines"```. 

The `tools::toTitleCase()` function returns what I expected, but it takes muuuch longer on a long string vector.

### Reprex
```r
str_to_title("saint vincent and the grenadines", locale = "en")
# [1] "Saint Vincent And The Grenadines"
str_to_title("the saint vincent and the grenadines", locale = "en")
# [1] "The Saint Vincent And The Grenadines"

# expected output
tools::toTitleCase("saint vincent and the grenadines")
# [1] "Saint Vincent and the Grenadines"
tools::toTitleCase("the saint vincent and the grenadines")
# [1] "The Saint Vincent and the Grenadines"
```

This issue is a possible duplicate of https://github.com/tidyverse/stringr/issues/330, but the focus there is another (all caps), so I hope it is okay to open a new issue with focus on articles in the middle of a sentence.

**Comment by hadley** [comment]
This is out of scope for `str_to_title()`, sorry. Maintaining a list of "unimportant" words would be a never ending task.
