### ISSUE TITLE
Incorrect behaviour when subsetting by empty vector with negate = TRUE

### ISSUE THREAD

**Issue by kendonB** [tidyverse/stringr#341]
When string subsetting a vector with an empty character vector and `negate = TRUE` I would expect the input vector to remain the same. It returns an empty character vector. The code is asking to remove matches, it finds no matches, so it should not remove anything.

``` r
stringr::str_subset("a", character(0), negate = TRUE)
#> character(0)
```

<sup>Created on 2020-07-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I would expect this:
``` r
stringr::str_subset("a", character(0), negate = TRUE)
#> {1] "a"
```

**Comment by cderv** [comment]
FWIW, `stringr` wraps the `stringi` function and the behavior of `stringr` is the one of `stringi`
``` r
stringi::stri_subset_regex("a", NULL, negate = TRUE)
#> character(0)
stringi::stri_subset_regex("a", character(0), negate = TRUE)
#> character(0)
stringi::stri_subset_regex("a", "", negate = TRUE)
#> Warning in stringi::stri_subset_regex("a", "", negate = TRUE): empty search
#> patterns are not supported
#> [1] NA
```

<sup>Created on 2020-07-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

You may open a FR there upstream also for this.

**Comment by gagolews** [comment]
stringi tries to be consistent with regards to handling of empty vectors with rule being *at least one empty, result is empty*.

This is exactly the behaviour of many base R vectorised operations, for example:

```r
> 2 + numeric(0)
numeric(0)

```

**Comment by hadley** [comment]
@gagolews FWIW the tidyverse is moving towards a simpler recycling rule, where we only recycle vectors of length 1 (so length zero is no longer a special case).

**Comment by hadley** [comment]
Closing since this isn't a bug, but an application of the recycling rules.
