### ISSUE TITLE
stringr fails in conda

### ISSUE THREAD

**Issue by AleSR13** [tidyverse/stringr#342]
Hello!! I am encountering a problem with stringr since yesterday. I always work in conda environments and my code invariably uses `stringr` for string manipulation. Since yesterday, I am trying to generate a new environment that uses `stringr` among other libraries. I do not get any installation errors and when I do `conda list`, both `stringr` and `stringi` seem to be there. However, when I try to load `stringr` in my scripts, I get the following error:

```
library(stringr)
```

> Error: package or namespace load failed for ‘stringr’ in dyn.load(file, DLLpath = DLLpath, ...): unable to load shared object '/path/to/my/conda/envs/r_reports/lib/R/library/stringi/libs/stringi.so': libicui18n.so.64: cannot open shared object file: No such file or directory

I have seen people reporting the same issue in previous releases and they often solve it by installing again through Rstudio. However, I rather not do that since the installation of the environment is part of my pipeline and it would need to be installed every time I run the same scripts. Any ideas on how to solve the issue? 

My yaml file (that I use to create the environment) looks like this:

> name: r_env
> channels:
>   - conda-forge
>   - r
>   - defaults
> dependencies:
>   - r-base=3.6
>   - rstudio
>   - r-dplyr
>   - r-ggplot2
>   - r-knitr
>   - r-lubridate
>   - r-purrr
>   - r-readr
>   - r-rmarkdown
>   - r-stringi
>   - r-stringr
>   - r-tibble
>   - r-gt
>   - r-plotly
>   - r-shiny

**Comment by gagolews** [comment]
Did you try reinstalling `stringi`?

**Comment by AleSR13** [comment]
Thanks a lot for your answer! Yes, reinstalling `stringi` is a temporary solution because indeed, my scripts can run after that. The main problem is that I write pipelines using `snakemake` and `conda` for other people in my institute. Every time they use it, they download my repository and create environments based on my yaml files... Every time the codes fails of course because of that error. I could include a re-installation of `stringi` within the pipeline, but it does not sound like the most clean or efficient solution. Anyway, I'll do that then! Thank you!

**Comment by hadley** [comment]
Unfortunately, I don't have anything to do with conda bundling, so you'll need to figure out who is responsible and ask them.

**Comment by NathanACO** [comment]
Hi,
I encountered the same issue when installing stringr in a conda environment.
Seems like conda install -c r r-stringr did not worked with stringr.
To fix this issue you have to download the stringr packages from https://cran.r-project.org/web/packages/stringr/index.html then in your conda environment you install it with install.packages ("stringr_1.5.0.tar.gz", repos = NULL, type = "source", dependencies = TRUE, INSTALL_opts = '--no-lock', configure.args='--disable-pkg-config').
