### ISSUE TITLE
A callback provided to `str_replace_all` is called in reverse order

### ISSUE THREAD

**Issue by Kodiologist** [tidyverse/stringr#343]
```r
> stringr::str_replace_all(c("abc", "xyz"), ".", print)
[1] "c"
[1] "b"
[1] "a"
[1] "z"
[1] "y"
[1] "x"
[1] "abc" "xyz"
```

The `replacement` function is called on `"abc"` before `"xyz"`, as one would expect, but within strings, the function is called for the last match first, the second-to-last match second, etc.

Whether this is changed or not (and I think it should be), the order of execution should be documented.

**Comment by hadley** [comment]
This is deliberate; otherwise figuring out the position of what you're replacing is v. tricky. It should be v. rare for the order of evaluation to make a difference, so I don't think this is worth documenting.

**Comment by Kodiologist** [comment]
I find that it's pretty common for the order of evaluation to matter, because it can come up whenever you're modifying variables outside the scope of the callback, as by collecting parts of what you're substituting into a list. It should definitely be documented if you're not going to fix it, because it's the opposite behavior from Perl and Python. I don't know of any other programming language or regex library that does this.

**Comment by Kodiologist** [comment]
Thanks.
