### ISSUE TITLE
Extract Regular Expression Groups: `str_group_extract()`

### ISSUE THREAD

**Issue by petermeissner** [tidyverse/stringr#346]
A common use case I stumble upon is to formulate a regular expression with several groups but only one of them being of interest for extraction. 

I herewith propose a function  `str_group_extract()` to solve this problem.

**Example Usage**

```r
strings <- paste(LETTERS, seq_along(LETTERS), sep = "_")
strings 
## [1] "A_1"  "B_2"  "C_3"  "D_4"  "E_5"  "F_6"  "G_7"  "H_8"  "I_9"  "J_10" "K_11" "L_12" "M_13" "N_14" "O_15" "P_16"
## [17] "Q_17" "R_18" "S_19" "T_20" "U_21" "V_22" "W_23" "X_24" "Y_25" "Z_26"
```

*no group specified*

```r
str_group_extract(strings, "([\\w])_(\\d+)")
## [1] "A_1"  "B_2"  "C_3"  "D_4"  "E_5"  "F_6"  "G_7"  "H_8"  "I_9"  "J_10" "K_11" "L_12" "M_13" "N_14" "O_15" "P_16"
## [17] "Q_17" "R_18" "S_19" "T_20" "U_21" "V_22" "W_23" "X_24" "Y_25" "Z_26"
```

*extract first group*

```r
str_group_extract(strings, "([\\w])_(\\d+)", 1)
## [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S" "T" "U" "V" "W" "X" "Y" "Z"
```

*extract second group*

```r
str_group_extract(strings, "([\\w])_(\\d+)", 2)
## [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15" "16" "17" "18" "19" "20" "21" "22"
## [23] "23" "24" "25" "26"
```

**Implementation**

```r
#' Extract Regular Expression Groups
#'
#' @param string string to extract from
#' @param pattern pattern with groups to match
#' @param group groups to extract
#' @param nas return NA values (TRUE) or filter them out (FALSE)
#'
#' @export
#'
#' @examples
#' 
#' strings <- paste(LETTERS, seq_along(LETTERS), sep = "_")
#' str_group_extract(strings, "([\\w])_(\\d+)")
#' str_group_extract(strings, "([\\w])_(\\d+)", 1)
#' str_group_extract(strings, "([\\w])_(\\d+)", 2)
#' 
str_group_extract <- 
  function(string, pattern, group = NULL, nas = TRUE){
    
    # handle group option
    if ( is.null(group) ){
      m <- stringr::str_match(string, pattern)[,1]
    } else {
      m <- stringr::str_match(string, pattern)[, (group + 1) ]
    }
    
    # handle 
    if ( nas == FALSE ) {
      m <- m[ !is.na(m) ]
    }
    
    # return
    m
  }
```

**Comment by cderv** [comment]
> A common use case I stumble upon is to formulate a regular expression with several groups but only one of them being of interest for extraction.

FWIW, there is a regex syntax to create a non capturing group `(?:...)` - it is the same as `(...)` but non capturing

    strings <- paste(LETTERS, seq_along(LETTERS), sep = "_")
    strings 
    #>  [1] "A_1"  "B_2"  "C_3"  "D_4"  "E_5"  "F_6"  "G_7"  "H_8"  "I_9"  "J_10"
    #> [11] "K_11" "L_12" "M_13" "N_14" "O_15" "P_16" "Q_17" "R_18" "S_19" "T_20"
    #> [21] "U_21" "V_22" "W_23" "X_24" "Y_25" "Z_26"

    # capture only first group
    stringr::str_match(strings, "([\\w])_(?:\\d+)")[, 2]
    #>  [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
    #> [20] "T" "U" "V" "W" "X" "Y" "Z"
    # capture only second group
    stringr::str_match(strings, "(?:[\\w])_(\\d+)")[, 2]
    #>  [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12" "13" "14" "15"
    #> [16] "16" "17" "18" "19" "20" "21" "22" "23" "24" "25" "26"

<sup>Created on 2020-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by petermeissner** [comment]
Most interesting 👍 

😕 **Confusingly they do not seem to work with `str_extract()`**:

```r 
strings <- paste(LETTERS, seq_along(LETTERS), sep = "_")
strings 
## [1] "A_1"  "B_2"  "C_3"  "D_4"  "E_5"  "F_6"  "G_7"  "H_8"  "I_9"  "J_10" "K_11" "L_12" "M_13" "N_14" "O_15" "P_16"
## [17] "Q_17" "R_18" "S_19" "T_20" "U_21" "V_22" "W_23" "X_24" "Y_25" "Z_26"

stringr::str_extract(strings, "([\\w])_(?:\\d+)")
## [1] "A_1"  "B_2"  "C_3"  "D_4"  "E_5"  "F_6"  "G_7"  "H_8"  "I_9"  "J_10" "K_11" "L_12" "M_13" "N_14" "O_15" "P_16"
## [17] "Q_17" "R_18" "S_19" "T_20" "U_21" "V_22" "W_23" "X_24" "Y_25" "Z_26"
```

**Comment by cderv** [comment]
No `str_extract` extracts the given pattern, it does not work with capturing group. 

    stringr::str_extract("A_1", "([\\w])_")
    #> [1] "A_"
    stringr::str_match("A_1", "([\\w])_")
    #>      [,1] [,2]
    #> [1,] "A_" "A"

<sup>Created on 2020-08-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

`str_extract` by default uses `stringi::str_extract_first_regex` and doc says

> Check out stri_match for the extraction of matches to individual regex capture groups.

So I believe with capture groups, one must use `str_match` or `str_match_all`

**Comment by petermeissner** [comment]
Sure.

... or, we introduce a new convenience wrapper bundling up the steps involved to make this work with `str_match()` - see the my implementation suggestion at the beginning.

**Comment by hadley** [comment]
I think this is out of scope for stringr — as @cderv points out you can already achieve what you want with `str_matches()` and non-capturing groups, or you can just do matrix indexing.

**Comment by petermeissner** [comment]
Fair enough.

For reference, this is part of {dsmisc} now: https://github.com/petermeissner/dsmisc/blob/master/R/str_group_extract.R
