### ISSUE TITLE
Request: str_chop() the function chops strings to equal length pieces

### ISSUE THREAD

**Issue by botan** [tidyverse/stringr#347]
It would be great a `stringr` function to chopping strings for fixed lengths.
There are a few ways to do this and the most easiest one which I found is shown below but I think still it is not too easy.

``` r
library(stringi)

str_chop <- function(x, n) {
  stri_sub(x, seq.int(1, stri_length(x), by = n), length = n)
}

# Example
str_chop("makechoppingeasy", 4)
#> [1] "make" "chop" "ping" "easy"
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's a good fit for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
