### ISSUE TITLE
regular expressions vignette: errors in 'phone' regex from 'Comments' section

### ISSUE THREAD

**Issue by david-romano** [tidyverse/stringr#349]
Although the example works correctly with the given phone number:
``` r
phone <- regex("
  \\(?     # optional opening parens
  (\\d{3}) # area code
  [)- ]?   # optional closing parens, dash, or space
  (\\d{3}) # another three numbers
  [ -]?    # optional space or dash
  (\\d{3}) # three more numbers
  ", comments = TRUE)

str_match("514-791-8141", phone)
#>      [,1]           [,2]  [,3]  [,4] 
#> [1,] "514-791-814" "514" "791" "814"
```
replacing the first dash by a space does not:
```r
str_match("514 791-8141", phone)
#>      [,1] [,2] [,3] [,4]
#> [1,] NA   NA   NA   NA
```
This is because the `comments = TRUE` argument strips the whitespace so that the equivalent non-commented regex is:
```r
phone <- "\\(?(\\d{3})[)-]?(\\d{3})[-]?(\\d{3})"
```
However, correcting this regex to match the original by re-inserting the space raises an error:
``` r
phone <- "\\(?(\\d{3})[)- ]?(\\d{3})[-]?(\\d{3})"
str_match("514 791-8141", phone)
#> Error in stri_match_first_regex(string, pattern, opts_regex = opts(pattern)): In a character range [x-y], x is greater than y. (U_REGEX_INVALID_RANGE)
```
since the dash is now interpreted as evidence of a range. 

Moving the dash to the front of the character class prevents this interpretation:
``` r
phone <- "\\(?(\\d{3})[-) ]?(\\d{3})[-]?(\\d{3})"
str_match("514 791-8141", phone)
#>      [,1]           [,2]  [,3]  [,4] 
#> [1,] "514 791-814" "514" "791" "814"
```
I wasn't previously aware of this behavior, so am not sure if it is addressed in either the documentation or in the 'R for Data Science' text, but that's a separate question and I'll check.

**Comment by hadley** [comment]
Thanks — should be better now.
