### ISSUE TITLE
Runaway regex results in str_detect taking thousands of times longer than grepl.

### ISSUE THREAD

**Issue by aaronrudkin** [tidyverse/stringr#350]
I wrote an apparently problematic regex. I can see from running some external regex debuggers that the regex has a loop built into it which is nasty and hard to resolve. Some online debuggers say it takes over a million steps to get an answer. My fault. Not looking for regex help. 

But this alerted me to the fact that in this pathological case, `str_detect` takes a very long time to fail, more than 30 seconds on my desktop (Ryzen 7 3700 at 4.1Ghz) -- compared to `grepl` (200 microseconds). I am assuming the cause is that grepl internally decide a certain step count before they will give up on attempting to resolve and then give up, but str_detect doesn't? That's just speculation on my part, I didn't go down the C rabbit hole. Oddly, neither produces an error. Neither a timeout error nor a parsing error.

I guess in order of preferences, mine would be:

Best: Have str_detect error quickly when it reaches a regex it has trouble parsing and tell me how to fix it (yeah, right!)
Good: Have str_detect's timeout or termination behaviour more closely match grepl's
OK: Add an argument to allow the user to terminate execution after a certain number of steps

The example below was generated using R 4.0.2 on Windows, stringr 1.4.0, bench 1.1.1. I've included two examples: one that is easily resolved by both (str_detect beats grepl!) and then the pathological case.

```r
library(tidyverse)
speaker_paren_regex <- "^[[:upper:]]((\\w|-)*[.,]? ?){1,4}, ((\\w|\\d|-|\\/|\\.)* ?){1,6}:" 
# n.b. for using external debuggers, the text here has the R-style double-escapes for character classes

text_ok <- "John Smith, ABC:"
bench::mark(
  str_detect = {str_detect(text_ok, speaker_paren_regex)},
  grepl = {grepl(speaker_paren_regex, text_ok)})
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 str_detect    140us    143us     6921.    18.8KB     0   
#> 2 grepl         215us    222us     4498.        0B     2.01

text_bad <- "Mittwoch, den 11.11.2015"
bench::mark(
  str_detect = {str_detect(text_bad, speaker_paren_regex)},
  grepl = {grepl(speaker_paren_regex, text_bad)})
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 str_detect      35s      35s    0.0285        0B        0
#> 2 grepl         230us    236us 4213.            0B        0
```

Edit: In hindsight this may be an upstream issue with `stringi::str_detect`

**Comment by gagolews** [comment]
I have responded in https://github.com/gagolews/stringi/issues/407  - there is no need to multiply issues without necessity.

**Comment by aaronrudkin** [comment]
Thank you for responding in stringi; per your response in stringi, stringi has support for a tuning parameter to terminate execution after a particular stack or time limit. So I guess the only thing that's relevant to stringr in this case is exposing that parameter in a clearer way (either by passing the `...` argument through to the wrapped `stringi::str_detect` function, or explicitly allowing an options argument, or perhaps by just making note that the wrapper does not wrap the tuning functionality).
