### ISSUE TITLE
Relicensing stringr

### ISSUE THREAD

**Issue by hadley** [tidyverse/stringr#351]
We are systematically re-licensing tidyverse and r-lib packages to use the MIT license, to make our package licenses as clear and permissive as possible. To do so, we need the approval of all copyright holders, which I have found by reviewing contributions from all all non-RStudio [contributors](https://github.com/tidyverse/stringr/graphs/contributors). @AmeliaMN, @amhrasmussen, @austin3dickey, @bfgray3, @carlganz, @ClaytonJY, @craigcitro, @dchiu911, @gagolews, @gnustats, @jonthegeek, @karldw, @lmullen, @pdelboca, @richardjtelford, @richierocks, @rjpat, @sastoudt, @seasmith, @Shians, @smbache, @stephlocke, @yutannihilation, would you permit us to re-license stringr with the MIT license? If so, please comment "I agree" below.

* [x] [@AmeliaMN](https://github.com/tidyverse/stringr/commits?author=AmeliaMN)  
* [x] [@amhrasmussen](https://github.com/tidyverse/stringr/commits?author=amhrasmussen)  
* [x] [@austin3dickey](https://github.com/tidyverse/stringr/commits?author=austin3dickey)  
* [x] [@bfgray3](https://github.com/tidyverse/stringr/commits?author=bfgray3)  
* [x] [@carlganz](https://github.com/tidyverse/stringr/commits?author=carlganz)  
* [x] [@ClaytonJY](https://github.com/tidyverse/stringr/commits?author=ClaytonJY)  
* [x] [@craigcitro](https://github.com/tidyverse/stringr/commits?author=craigcitro)  
* [x] [@dchiu911](https://github.com/tidyverse/stringr/commits?author=dchiu911)  
* [x] [@gagolews](https://github.com/tidyverse/stringr/commits?author=gagolews)  
* [x] [@gnustats](https://github.com/tidyverse/stringr/commits?author=gnustats)  
* [x] [@jonthegeek](https://github.com/tidyverse/stringr/commits?author=jonthegeek)  
* [x] [@karldw](https://github.com/tidyverse/stringr/commits?author=karldw)  
* [x] [@lmullen](https://github.com/tidyverse/stringr/commits?author=lmullen)  
* [x] [@pdelboca](https://github.com/tidyverse/stringr/commits?author=pdelboca)  
* [x] [@richardjtelford](https://github.com/tidyverse/stringr/commits?author=richardjtelford)  
* [x] [@richierocks](https://github.com/tidyverse/stringr/commits?author=richierocks)  
* [x] [@rjpat](https://github.com/tidyverse/stringr/commits?author=rjpat)  
* [x] [@sastoudt](https://github.com/tidyverse/stringr/commits?author=sastoudt)  
* [x] [@seasmith](https://github.com/tidyverse/stringr/commits?author=seasmith)  
* [x] [@Shians](https://github.com/tidyverse/stringr/commits?author=Shians)  
* [x] [@smbache](https://github.com/tidyverse/stringr/commits?author=smbache)  
* [x] [@stephlocke](https://github.com/tidyverse/stringr/commits?author=stephlocke)  
* [x] [@yutannihilation](https://github.com/tidyverse/stringr/commits?author=yutannihilation)

**Comment by jonthegeek** [comment]
I agree.

**Comment by richardjtelford** [comment]
I agree.

**Comment by ClaytonJY** [comment]
I agree.

**Comment by yutannihilation** [comment]
I agree.

**Comment by stephlocke** [comment]
I agree

**Comment by austin3dickey** [comment]
I agree

**Comment by sastoudt** [comment]
I agree.

**Comment by craigcitro** [comment]
I agree.

**Comment by karldw** [comment]
I agree

**Comment by carlganz** [comment]
I agree

**Comment by pdelboca** [comment]
I agree

**Comment by gagolews** [comment]
I agree.

**Comment by rjpat** [comment]
I agree.

**Comment by bfgray3** [comment]
I agree

**Comment by lmullen** [comment]
I agree.

**Comment by dchiu911** [comment]
I agree

**Comment by seasmith** [comment]
I agree

**Comment by Shians** [comment]
I agree

**Comment by amhrasmussen** [comment]
I agree

**Comment by AmeliaMN** [comment]
I agree

**Comment by batpigandme** [comment]
Hi, @gnustats, @richierocks, and @smbache,
We'd love to get your agreement please, if you could take a look when you have a chance. 🙂
Thanks!

**Comment by richierocks** [comment]
I agree

**Comment by hadley** [comment]
@gnustats and @smbache agreed via email.
