### ISSUE TITLE
Adding examples of stringr functions inside of dplyr pipelines to roxygen comments

### ISSUE THREAD

**Issue by joshyam-k** [tidyverse/stringr#352]
I’ve found that integrating calls to stringr functions inside of dplyr pipelines can be tricky for many learners. I think it could be helpful to add an example inside of the roxygen2 documentation for str_* functions that integrates the function into a dplyr::mutate( ) or dplyr::filter( ) call. 

For example, in the current docs https://github.com/tidyverse/stringr/blob/5ddf8cea0b5712639d12c8c77d74a6b050b68a52/R/replace.r#L1-L65 for str_replace(), adding a few roxygen comments along the lines of:

```r
#' # When working with dataframes, stringr functionality
#' # can be used inside of dplyr pipelines
#' library(dplyr)
#'
#' fruits_df <- data.frame(
#'   type = c("apple", "banana", "pear", "pineapple")
#' )
#'
#' fruits_df %>%
#'   mutate(type = str_replace(type, "a", "-"))
```
could go a long way in helping people understand the function more easily.

Would you be willing to consider a PR adding these sorts of examples to the docs for relevant str_* functions? I understand that this would mean adding dplyr to Suggests, but I think this documentation could be extremely helpful.

@simonpcouch

**Comment by hadley** [comment]
I currently see this as out of scope for stringr docs.
