### ISSUE TITLE
str_rank()?

### ISSUE THREAD

**Issue by courtiol** [tidyverse/stringr#353]
R base as sorting, ordering and ranking functions. Each fits a different purpose.
As far as I can see, stringr (and stringi) don't have ranking versions of their sorting and ordering functions.
One motivation could be obtaining natural sorting in dplyr:
``` r
library(dplyr, warn.conflicts = FALSE)
foo <- tibble(x = c("A100", "B3", "A1", "A2", "A10", "A11", "A100C", "AA9"))

foo %>%
  arrange(x)
#> # A tibble: 8 x 1
#>   x    
#>   <chr>
#> 1 A1   
#> 2 A10  
#> 3 A100 
#> 4 A100C
#> 5 A11  
#> 6 A2   
#> 7 AA9  
#> 8 B3

str_rank <- function(x, ...) match(x, stringr::str_sort(x, ...))

foo %>%
  arrange(str_rank(x, numeric = TRUE))
#> # A tibble: 8 x 1
#>   x    
#>   <chr>
#> 1 A1   
#> 2 A2   
#> 3 A10  
#> 4 A11  
#> 5 A100 
#> 6 A100C
#> 7 AA9  
#> 8 B3
```

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Not sure this is needed in stringi since people using stringi should be capable to define, with no difficulty, a little function like the one above on the fly, but with stringr aiming at being more accessible it seems to make sense to me...

**Comment by courtiol** [comment]
Note: @hadley suggested to me that `stringi::stri_sort_key()` does that already, but I cannot make it work, so it does not seem very user friendly.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, since there doesn't seem to be much interest in it, I don't think it's a good fit for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by hadley** [comment]
Ok, I just needed this so I do now think it's worthwhile.
