### ISSUE TITLE
regex doesn't work with matches but with str_detect

### ISSUE THREAD

**Issue by jonas-hag** [tidyverse/stringr#357]
I've encountered the problem that the regex `"[\\d]1"` doesn't work with `matches`, I think it is the "`[\\d]`" part that makes problems. If you remove the square brackets, it works (and I think they are not necessarily needed). However, if I use the regex with `str_detect` from `stringr`, it works.
``` r
library(dplyr)
library(stringr)

testdf <- data.frame(a_21 = 1, a_22 = 2)

testdf %>% 
  select(matches("[\\d]1"))
#> data frame with 0 columns and 1 row

testdf %>% 
  select(matches("\\d1"))
#>   a_21
#> 1    1

str_detect(colnames(testdf), "[\\d]1")
#> [1]  TRUE FALSE

str_detect(colnames(testdf), "\\d1")
#> [1]  TRUE FALSE
```

<sup>Created on 2020-12-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`R 4.0.2` and `dplyr 1.0.2`

**Comment by jonas-hag** [comment]
It seems that it more has to do with `R`s implementation of the [POSIX 1003.2 standard](https://www.regular-expressions.info/rlanguage.html). If my understanding of `[]` is correct, it defines a character class and matches one character out of this character class. `\d` (or for R `\\d`) is itself already a character class, so the square brackets are not needed but it should work (while [not recommend as in this SO answer](https://stackoverflow.com/a/27791811/12647315)). Because of `R`'s implementation, the website mentioned above https://www.regular-expressions.info/rlanguage.html recommends to always use `perl = TRUE`. This leads to the use of the PCRE library that is apparently more "standard". And indeed, the result is as expected:

``` r
library(tidyselect)
library(stringr)

x <- c("a_21", "a_22", "\\d")
matches("[\\d]", vars = x)
#> [1] 3
matches("\\d", vars = x)
#> [1] 1 2

matches("[\\d]", vars = x, perl = TRUE)
#> [1] 1 2
matches("\\d", vars = x, perl = TRUE)
#> [1] 1 2

grepl("[\\d]", x)
#> [1] FALSE FALSE  TRUE
grepl("\\d", x)
#> [1]  TRUE  TRUE FALSE

grepl("[\\d]", x, perl = TRUE)
#> [1]  TRUE  TRUE FALSE
grepl("\\d", x, perl = TRUE)
#> [1]  TRUE  TRUE FALSE

str_detect(x, "[\\d]")
#> [1]  TRUE  TRUE FALSE
str_detect(x, "\\d")
#> [1]  TRUE  TRUE FALSE
```

<sup>Created on 2020-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Alternatively, you could use `[:digit:]` instead of `\\d`, however it has to be wrapped in square brackets again (so also not super intuitively):
``` r
x <- c("a_21", "a_22", "\\d")
grepl("[[:digit:]]", x)
#> [1]  TRUE  TRUE FALSE
```

<sup>Created on 2020-12-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Therefore, I would say that it's not a bug in `stringr`, but it results from `stringr`'s use of `perl` like regexes (or more precisely, the use of the underlying `stringi`/`ICU` libraries). Maybe you could mention this behaviour in the section where `stringr` is compared to the base functions?

**Comment by gagolews** [comment]
`stringr` uses `stringi`, and `stringi` relies on the ICU regex engine, which is a different one from PCRE/PCRE2. When in doubt, refer to http://userguide.icu-project.org/strings/regexp.
According to http://userguide.icu-project.org/strings/regexp, `\d` can be used inside character sets as well, so `\d` and `[\d]` are equivalent.

```
> stringi::stri_extract_all_regex("123\\a\\\\bcdef\\d", c("\\d", "[\\d]"))
[[1]]
[1] "1" "2" "3"

[[2]]
[1] "1" "2" "3"
```

However, `matches()` from `tidyselect` does not rely on `stringr`, but on `base::match()`. Therefore, it's not an issue related to `stringer` imo.

**Comment by jonas-hag** [comment]
Thanks for your comment @gagolews ! I agree that it is not an issue related to `stringr`. As I dug deeper (see my second post) it's actually not the difference between the ICU engine and  PCRE/PCRE2 but the difference to the `R` POSIX 1003.2 standard implementation which seems to be a bit "special" (and is the default in base R).

Maybe you could mention the use of the ICU engine in `stringr` compared to `R`s own implementation/PCRE in the vignette "From base R" to make it (absolutely) clear? Otherwise the issue can be closed.

**Comment by hadley** [comment]
This isn't really to do with stringr at all, since (to keep dependencies low) tidyselect uses base R.
