### ISSUE TITLE
`str_count` but to count all (any?) occurrences from a vector of patterns.  

### ISSUE THREAD

**Issue by slee981** [tidyverse/stringr#358]
Using `str_count(...)` with a vector of inputs for the pattern produces the following output: 

```r
fruit <- c("apple", "banana", "pear", "pineapple")

str_count(fruit, c("a", "b", "p", "p"))
#> [1] 1 1 1 3
```

I would have expected the result to return, for example:

```r
fruit <- c("apple", "banana", "pear", "pineapple")

str_count_all(fruit, c("a", "b", "p"))
#> [1] 3 4 2 4
```

Does that make sense to anyone else? To illustrate, a first pass implementation would be something like: 

```r
str_count_all <- function(string, patterns) {
    ct <- 0 
    for (p in patterns) {
        ct = ct + str_count(string, p)
    }
    return(ct)
}
```

I'm sure the implementation could improve, and I'm not sure if the name `str_count_all` or `str_count_any` makes more sense to capture the spirit of it, but wanted to see if there was any interest in this functionality.

**Comment by rjpat** [comment]
I think because of the way R recycles vector it compares it against each item, rather than compare them all as you expected. If the vector was collapsed into a regex using the `|` character as an _or_ may give you what you were expecting?
``` r
library(stringr)

fruit <- c("apple", "banana", "pear", "pineapple")

str_c(c("a", "b", "p", "p"), collapse = "|")
#> [1] "a|b|p|p"

str_count(fruit, str_c(c("a", "b", "p", "p"), collapse = "|"))
#> [1] 3 4 2 4
```

<sup>Created on 2021-01-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
This is the way that all stringr functions work. Unfortunately I don't think it's worthwhile to implement `str_count_any/all()`: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
