### ISSUE TITLE
`str_replace_all` fails for large inputs

### ISSUE THREAD

**Issue by programLyrique** [tidyverse/stringr#361]
`str_replace_all` fails when the input is large. It should replace all the patterns it found but does not replace at all.

```r
h <- function(n) { str_replace_all(str_c(rep.int("2", n), collapse = ","), "(?=[^[:alpha:]])(?:-?\\d*(\\.\\d*)?L?,\\s*)*-?\\d+(\\.\\d*)?L?", replacement = "1") }

h(124998) # Succeeds, returns "1"
h(124999) # Fails, returns "2, 2, 2, ..., 2"
```
I obtained `n = 124999`  with a dichotomic search, i.e. 249 998 characters. On `str_replace_all(str_c(rep.int("456", n), collapse = ",")`, it fails for `n = 62500`, i.e. 250 000 characters.  So there seems to be a hard limit with this pattern, around 250 000 characters.

Note also that `gsub` has no problems to do replacing even with larger inputs:

```r
g <- function(n) { gsub(x = str_c(rep.int("2", n), collapse = ","), pattern = "(?=[^[:alpha:]])(?:-?\\d*(\\.\\d*)?L?,\\s*)*-?\\d+(\\.\\d*)?L?", replacement = "1", perl = TRUE) }

g(124999) # returns "1"

g(1000000) # returns "1"
```

```r
packageVersion("stringr")
[1] ‘1.4.0’
```

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment]
Thinking about this more, this is very unlikely to be a problem with stringr, and is instead probably from the underlying stringi package. I'd suggest filing a reprex at https://github.com/gagolews/stringi.
