### ISSUE TITLE
return matrices of all NA rows/cols for all no-matches

### ISSUE THREAD

**Issue by maxheld83** [tidyverse/stringr#366]
`str_extract_all(simplify = TRUE)` currently returns what might be considered inconsistently, depending on whether there is at least one match:

``` r
# one match: returns matrix with empty string for no matches
stringr::str_extract_all(c("foo", "bar"), pattern = "bar", simplify = TRUE)
#>      [,1] 
#> [1,] ""   
#> [2,] "bar"
# no matches: returns matrix with 0 cols
stringr::str_extract_all("foo", pattern = "bar", simplify = TRUE)
#>     
#> [1,]
stringr::str_extract_all(c("foo", "zap"), pattern = "bar", simplify = TRUE)
#>     
#> [1,]
#> [2,]
```

<sup>Created on 2021-03-10 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

I'd imagine that this is simply because of base R, which will drop empty (character) vectors.
However, stringr already seems to be "repair" this base R behavior when there are at least *some* matches:

``` r
# 0-length char just gets dropped
c("foo", character())
#> [1] "foo"
# resulting 0-length char gets changed to ""
stringr::str_extract_all(c("foo", "bar"), pattern = "bar", simplify = TRUE)
#>      [,1] 
#> [1,] ""   
#> [2,] "bar"
```

The [docs](https://stringr.tidyverse.org/articles/from-base.html) also state:

> Base R requires the combination of `regexpr()` with `regmatches()`; but note that the strings without matches are dropped from the output. stringr provides `str_extract()` and `str_extract_all()`, and the output is always the same length as the input.

It might be great if stringr could always hide away this base R behavior and always return at least a 1x1 matrix.
Otherwise, whatever function is calling the result and need to take special precaution for this special case (`x[, 1]` might fail, for example).
I'm also not sure how whether this behavior could be considered length-stable.
(It *is* type-stable, because the result *is* still a matrix).

**Comment by maxheld83** [comment]
argh, I see this issue may be stemming from stringi, not stringr.
Will investigate, link and then close.

**Comment by maxheld83** [comment]
The "problem" (if that's what it is) is, in fact, in stringr:

https://github.com/tidyverse/stringr/blob/1f03eb02b68922d24bb37b326c85dbae57f7d2f1/R/extract.r#L44-L53

`str_extract_all()` runs `stringi::stri_extract_all()` with `omit_no_match = TRUE`, which causes the `character()`s (rather than `NA`), which, in turn via base R, causes the 0-col matrices.

The behavior can be reproduced in stringi with the argument:

``` r
# default setting
stringi::stri_extract_all_regex("foo", pattern = "bar", simplify = TRUE)
#>      [,1]
#> [1,] NA
# omit no matches
stringi::stri_extract_all_regex("foo", pattern = "bar", omit_no_match = TRUE, simplify = TRUE)
#>     
#> [1,]
```

This setting seems to have been introduced way back in https://github.com/tidyverse/stringr/commit/95b418adc0c2cf45cd21ec3cd9f4ca213f801fe8 and is explicitly tested for, so there was probably a good reason for it.

However, the test only covers `simplify = FALSE`, where the `character()`, as a list element, doesn't violate length stability.
Under `simplify = TRUE`, a `character()` will be dropped, and so I think the argument for (at least) setting `omit_no_match = !simplify`.

I'm going to add an experimental PR to that effect.

**Comment by maxheld83** [comment]
the same problem (?) also affects `stringr::str_match_all()`:

``` r
stringr::str_match_all(c("a", "foo"), "(a)(b)?")
#> [[1]]
#>      [,1] [,2] [,3]
#> [1,] "a"  "a"  NA  
#> 
#> [[2]]
#>      [,1] [,2] [,3]
```

<sup>Created on 2021-03-11 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Here too, when *all* elements of the pattern are no matches, the internal `omit_no_match = TRUE` the entire matrix row (because of `character()`) gets dropped, making the function harder to work with or arguably length-unstable-ish.

https://github.com/tidyverse/stringr/blob/1f03eb02b68922d24bb37b326c85dbae57f7d2f1/R/match.r#L54-L58

Will address in incoming PR.

**Comment by maxheld83** [comment]
and `stringr::str_locate_all()`:

``` r
stringr::str_locate_all("foo", "bar")[[1]]
#>      start end
```

So this is now everywhere where `omit_no_match` was set in the package.

**Comment by hadley** [comment]
I think the existing behaviour of `str_extract_all()` with `simplify = TRUE` is consistent — it has one row for each element of `x`, and the number of columns is the maximum number of matches in any row. I think applying the constraint that it always has at least 1 column makes it less consistent, not more.
