### ISSUE TITLE
`str_squish()` does not squish 

### ISSUE THREAD

**Issue by phargarten2** [tidyverse/stringr#369]
Thank you for implementing **stringr** and allowing intuitive functions for managing strings as easily as possible. 

The documentation states that `str_squish()` removes _repeated_ whitespace inside a string. I attempted to apply the function to the column names of a data frame, which is given below. `str_squish()` does not remove the spaces between "Comments" and "(".  However, using `str_replace_all()` works fine. Could this be an issue with `str_squish()`? 

```{r}
library(stringr)
text <-  c("Lot_number","Range","Replicate","y1","log_y1","Comments (1)","y2","log_y2","Comments (2)")
text
#> [1] "Lot_number"   "Range"        "Replicate"    "y1"           "log_y1"      
#> [6] "Comments (1)" "y2"           "log_y2"       "Comments (2)"

str_squish(text)   #does not work
#> [1] "Lot_number"   "Range"        "Replicate"    "y1"           "log_y1"      
#> [6] "Comments (1)" "y2"           "log_y2"       "Comments (2)"

str_replace_all(text, regex("\\s*"), "")   #works as expected
#> [1] "Lot_number"  "Range"       "Replicate"   "y1"          "log_y1"     
#> [6] "Comments(1)" "y2"          "log_y2"      "Comments(2)"
```

The function `str_squish()` is written as 
```
str_squish
#> function (string) 
#> {
#>     stri_trim_both(str_replace_all(string, "\\s+", " "))
#> }
#> <bytecode: 0x0000000015e12c08>
#> <environment: namespace:stringr>
```

Package info
```
xfun::session_info("stringr")
#> R version 4.0.4 (2021-02-15)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Locale:
#>   LC_COLLATE=English_United States.1252 
#>   LC_CTYPE=English_United States.1252   
#>   LC_MONETARY=English_United States.1252
#>   LC_NUMERIC=C                          
#>   LC_TIME=English_United States.1252    
#> 
#> Package version:
#>   glue_1.4.2      graphics_4.0.4  grDevices_4.0.4 magrittr_2.0.1 
#>   methods_4.0.4   stats_4.0.4     stringi_1.5.3   stringr_1.4.0  
#>   tools_4.0.4     utils_4.0.4
```

**Comment by smbache** [comment]
"`str_squish()` also reduces *repeated* whitespace inside a string."

**Comment by phargarten2** [comment]
@smbache, good catch! I updated the issue above.

**Comment by hadley** [comment]
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by smbache** [comment]
Seems to me there is no issue - there's no repeated whitespace in the example.

**Comment by hadley** [comment]
@smbache ok, thanks!

**Comment by phargarten2** [comment]
Thank you for looking at this. I wrote the original example using the **reprex** package. The issue is that I had to use a different regular expression in `string_replace_all()` to remove the spaces instead of using `str_squish()`. I updated the example above for clarity. I hope that this helps.
