### ISSUE TITLE
Idea: add str_ starts_with(), str_ends_with(), etc.

### ISSUE THREAD

**Issue by elbersb** [tidyverse/stringr#373]
While teaching `stringr` and `tidyselect` I was wondering whether it would be useful to have a more consistent API between the two. For instance, `tidyselect` has `matches`, but there is no `str_matches` in `stringr`. 

Adding the following functions to `stringr` would be a nice usability improvement, but maybe it would also clutter the API too much. All of these would be wrappers around `str_detect`:

- `str_starts_with()`
- `str_ends_with()`
- `str_contains()`
- `str_matches()`

**Comment by elbersb** [comment]
Just remembered that there is `str_match` of course, but with a much different purpose. So that one would be confusing.

**Comment by hadley** [comment]
There are already `str_starts()` and `str_ends()`, and `str_contains()` and `str_matches()` would just be variants of `str_detect()`.

**Comment by elbersb** [comment]
Yes, that was the point—that the names are different. :)
