### ISSUE TITLE
Feature suggestions: str_to_title() option to not capitalize articles, conjunctions, etc

### ISSUE THREAD

**Issue by jzadra** [tidyverse/stringr#390]
It would be great to have an option in `str_to_title()` to not capitalize articles and [conjunctions](https://www.grammarly.com/blog/conjunctions/#:~:text=Coordinating%20conjunctions%20allow%20you%20to,using%20the%20mnemonic%20device%20FANBOYS.), prepositions, etc, similar to the [APA guide](https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case) and other common capitalization rules.

I.e., “but,” “for,” “if,” “nor,” “or,” “so,” “yet”, "and", “as,” “at,” “by,” “for,” “in,” “of,” “off,” “on,” “per,” “to,” “up,” “via”.

And it should ignore the first word of a title for these rules of course.

**Comment by hadley** [comment]
This is out of scope for `str_to_title()`, sorry. Title case is inherently poorly defined, and `str_to_title()` isn't going to try and handle every exception.
