### ISSUE TITLE
Allow to keep as factor (and keep levels) when using stringr modifiers.

### ISSUE THREAD

**Issue by orgadish** [tidyverse/stringr#394]
I often have factor data that I want to rework slightly for a plot. When I use something like `str_to_upper` or `str_replace` to do so, I lose the factor levels.

While I certainly not have thought through all of the implications, it seems that implementing this simply requires applying the same function to the levels and reattaching (or keeping) them. From a development perspective, I don't know if this is best handled within `forcats` or `stringr`, but as an end-user it feels like it would ideally be an argument within the current `stringr` functions (e.g. `.keep_levels`).

``` r
library(tidyverse)

iris_with_reordered_levels <- iris %>% 
  mutate(across(Species, fct_relevel, "virginica"))

iris_with_reordered_levels %>% 
  pull(Species) %>% 
  levels    
#> [1] "virginica"  "setosa"     "versicolor"

iris_with_reordered_levels %>% 
  mutate(across(Species, str_to_upper)) %>% 
  pull(Species) %>% 
  levels    
#> NULL


fct_str_to_upper <- function(.f, ...) {
  new_levels <- str_to_upper(levels(.f), ...)
  new_str <- str_to_upper(.f, ...)
  factor(new_str, levels=new_levels)
}


iris_with_reordered_levels %>% 
  mutate(across(Species, fct_str_to_upper)) %>% 
  pull(Species) %>% 
  levels
#> [1] "VIRGINICA"  "SETOSA"     "VERSICOLOR"
```

<sup>Created on 2021-09-04 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
stringr functions always return strings; if you want to modify the levels of a factor, I'd suggesting combining a stringr function with `forcats::fct_relabel()`:

``` r
forcats::fct_relabel(head(iris$Species), stringr::str_to_upper)
#> [1] SETOSA SETOSA SETOSA SETOSA SETOSA SETOSA
#> Levels: SETOSA VERSICOLOR VIRGINICA
```

<sup>Created on 2021-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
