### ISSUE TITLE
str_order gives unexpected ordering

### ISSUE THREAD

**Issue by arisp99** [tidyverse/stringr#395]
In some instances, `str_order` gives an ordering that does not match the order given by `stri_rank`. The `stri_rank` order is the output I would expect given the input string.

``` r
test <- c("S-23", "S-15", "S-55", "S-5", "S-48")
test
#> [1] "S-23" "S-15" "S-55" "S-5"  "S-48"
stringr::str_order(test, numeric = TRUE)
#> [1] 4 2 1 5 3
stringi::stri_rank(test, numeric = TRUE)
#> [1] 3 2 5 1 4
```

Interestingly, this behavior is not seen for `str_sort` and `stri_sort`. Furthermore, if the order of the input string is changed, there is no longer a difference between outputs.

``` r
test
#> [1] "S-23" "S-15" "S-55" "S-5"  "S-48"
stringr::str_sort(test, numeric = TRUE)
#> [1] "S-5"  "S-15" "S-23" "S-48" "S-55"
stringi::stri_sort(test, numeric = TRUE)
#> [1] "S-5"  "S-15" "S-23" "S-48" "S-55"

test2 <- c("S-23", "S-15", "S-5", "S-48", "S-55")
test2
#> [1] "S-23" "S-15" "S-5"  "S-48" "S-55"
stringr::str_order(test2, numeric = TRUE)
#> [1] 3 2 1 4 5
stringi::stri_rank(test2, numeric = TRUE)
#> [1] 3 2 1 4 5
```

<sup>Created on 2021-09-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I am using version 1.4.0 of `stringr` and version 1.7.4 of `stringi`.

Any insight would be greatly appreciated!

**Comment by hadley** [comment]
I don't think you should expect order and rank to match. The constraint on `str_order()` is that `str_sort(x)` = `x[str_order(x)]` which is what you get:

``` r
library(stringr)

test <- c("S-23", "S-15", "S-55", "S-5", "S-48")
test[str_order(test, numeric = TRUE)]
#> [1] "S-5"  "S-15" "S-23" "S-48" "S-55"
str_sort(test, numeric = TRUE)
#> [1] "S-5"  "S-15" "S-23" "S-48" "S-55"
```

<sup>Created on 2021-11-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by arisp99** [comment]
That makes sense, thank you! `str_order()` then gives the ordering used for subsetting, i.e. which element should come 1st, which should come 2nd, etc., whereas `stri_rank()` indicates which element would come 1st, 2nd, etc. in a sorted vector.
```r
test <- c("S-23", "S-15", "S-55", "S-5", "S-48")
test
#> [1] "S-23" "S-15" "S-55" "S-5"  "S-48"
stringr::str_order(test, numeric = TRUE)
#> [1] 4 2 1 5 3 (4th element should be 1st, then 2nd element, etc.)
stringi::stri_rank(test, numeric = TRUE)
#> [1] 3 2 5 1 4 (the 1st element should be 3rd, the 2nd element should be 2nd, etc.)
```
