### ISSUE TITLE
Str_sub causes fatal error with Rstudio 

### ISSUE THREAD

**Issue by bensenmansen** [tidyverse/stringr#397]
When working with stringr the function str_sub always ends in fatal error. Reinstalling stringr or change of directory for packages did not help. Other functions work fine.

R 4.1.0
![Unbenannt](https://user-images.githubusercontent.com/87663755/133996508-9fe5ab00-c6e2-46d6-ad00-3070631e32a7.PNG)

RStudio 1.4.1717

```r
library(stringr)

str_detect("Hallo", pattern = "llo")
str_count("Hallo")
str_extract("Hallo", "llo")

str_sub("Hallo", start = 0, end = 3) 
```

**Comment by gagolews** [comment]
Could you please reinstall stringi (`install.packages("stringi")`), restart R, and run this example again?

**Comment by bensenmansen** [comment]
Thank you very much for the quick response. Reinstalling "stringi" did fix this issue indeed. Thanks.
