### ISSUE TITLE
str_sort with parameter numeric = TRUE doesn‘t correctly sort negative values

### ISSUE THREAD

**Issue by deschen1** [tidyverse/stringr#402]
```
library(stringr)
x <- c('-1', '0', '-10', '5', '3.14')
str_sort(x, numeric = TRUE)
```

gives wrong result:

`[1] "-1"   "-10"  "0"    "3.14" "5"`

expected result:

`[1] "-10"   "-1"  "0"    "3.14" "5"`

**Comment by gagolews** [comment]
I'm afraid the handing of negative numbers is not supported.

You can of course try `as.character(sort(as.numeric(x)))` or handle the strings featuring the minus sign separately.

**Comment by deschen1** [comment]
Sure, in this edge case I could just convert to numeric first and then sort them, but generally I thought that if stringr claims to sort strings numerically, then it should support negative numbers as well. So if possible the functionality could be added. Or at least the help page of str_sort should mention that negative numbers are not supported (sorry if it is already in the documentation and I've just missed it!).
