### ISSUE TITLE
`str_count()` with the "pattern" being consist of multiple AND, OR

### ISSUE THREAD

**Issue by Yingjie4Science** [tidyverse/stringr#405]
Hi, I would like to use str_count() to detect how many string matches in a sentence, and the `pattern` will look like this:  **(('a1|a2|a3') AND ('b1|b2|b3')) OR ('aa|bb')**

I expect to see the following code will return 2 matches. Is this possible?

`text <- "a1 and b1 are friends, and aa is also a good friend"`

`stringr::str_count(string = text, regex(pattern = pattern, ignore_case = T))`

**Comment by hadley** [comment]
This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
