### ISSUE TITLE
str_flatten: unused argument error

### ISSUE THREAD

**Issue by wdenton** [tidyverse/stringr#412]
With R 4.1.1 (on Ubuntu 20.04):

```
> library(stringr)
> packageVersion("stringr")
[1] ‘1.4.0’
> str_flatten(letters[1:5], ", ", ", and ")
Error in str_flatten(letters[1:5], ", ", ", and ") : 
  unused argument (", and ")
```

The sample line is from the [str_flatten docs](https://stringr.tidyverse.org/reference/str_flatten.html).  Surely it's passing all the tests and this is some problem on my end ... but what?  I can't figure out what's happening, so I report this in case it really is a bug.

**Comment by hadley** [comment]
It's because the docs are for the dev version because I forgot to do separate websites for the CRAN and dev version. This will resolve naturally in the near future when the next release of stringr comes out.
