### ISSUE TITLE
str_to_title(): stop words (e.g. of, the, etc.) should be given option to be excluded 

### ISSUE THREAD

**Issue by PursuitOfDataScience** [tidyverse/stringr#414]
Maybe in the future version of stringr, `str_to_title()` should be added an extra argument, offering an option of whether some basic stop words should be excluded from capitalizing the first letter. Here is an example that clarify what I mean. 
```
str_to_title("the person of the year") 
```
should be "The Person of the Year" rather than "The Person Of The Year" as it outputs at the moment. 

Thanks!

**Comment by rjpat** [comment]
There have been a few previous requests but the underlying `{stringi}` function does not have the capability and it has been previously mentioned as out of scope for `{stringr}`

Similar issue https://github.com/tidyverse/stringr/issues/390

**Comment by PursuitOfDataScience** [comment]
Thanks for the response. I thought there would be people who would have the same feeling as I do, as `str_to_title()` is such a nifty function, and it would be better to have it.

**Comment by hadley** [comment]
Yeah, it's out of scope, sorry.
