### ISSUE TITLE
Regular expressions with `rex()` do not work anymore

### ISSUE THREAD

**Issue by mgirlich** [tidyverse/stringr#433]
``` r
stringr::str_detect("apple", rex::rex(maybe("a")))
#> Error in `type()`:
#> ! `pattern` must be a string
```

<sup>Created on 2022-02-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is because  the change to the class names

> `regex()` and friends now generate class names with `stringr_` prefix

and `stringr::type()` is not exported so the `rex` package cannot create a correct `type()` method.

**Comment by hadley** [comment]
Maybe the easiest fix would be to just keep `type.regex <- function(x) "regex"` ?
