### ISSUE TITLE
Error: 'str_split_n' is not an exported object from 'namespace:stringr'

### ISSUE THREAD

**Issue by dsg38** [tidyverse/stringr#434]
Function 'str_split_n' is documented here (v1.4.0.9000)
https://stringr.tidyverse.org/reference/str_split.html

I have v1.4, but i get the error:
`Error: 'str_split_n' is not an exported object from 'namespace:stringr'`

Thanks

**Comment by sverchkov** [comment]
Looks like the documentation is ahead of the stable release. `str_split_n` isn't in yet, and judging by the source it might not end up being named that.
FWIW you can achieve the same functionality with `str_split_fixed(x, delim, n+1)[,n]`
