### ISSUE TITLE
Typo in stringr documentation page

### ISSUE THREAD

**Issue by bbarros50** [tidyverse/stringr#438]
There is a typo on the [stringr documentation page](https://stringr.tidyverse.org/) (see below). It looks like this is the same issue that was fixed in #406 .

```{r}
# The easiest way to get dplyr is to install the whole tidyverse:
install.packages("tidyverse")

# Alternatively, install just dplyr:
install.packages("dplyr")
```

**Comment by batpigandme** [comment]
Yes, it looks like this was fixed in https://github.com/tidyverse/stringr/commit/dcebf2822fad9591cb53c9ab0881cf4d93013746, but that the actual pkgdown site has not been rebuilt yet, so it hasn't propagated.

**Comment by batpigandme** [comment]
Hmm. Actually, it looks like the page was last built on January 23rd (and that commit was January 3rd), so I'm not sure why that's not showing in the pkgdown site.

**Comment by hadley** [comment]
Fixed now
