### ISSUE TITLE
`locale = "C"` is ignored in `str_sort` and `str_order`

### ISSUE THREAD

**Issue by Kodiologist** [tidyverse/stringr#440]
```
> tv <- c("a", "A", "ab", "B")
> withr::with_collate("C", sort(tv))
[1] "A"  "B"  "a"  "ab"
> stringr::str_sort(tv, locale = "C")
[1] "a"  "A"  "ab" "B" 
```

See https://stackoverflow.com/q/4245196.

**Comment by hadley** [comment]
```R
"C" %in% stringi::stri_locale_list() 
#> [1] FALSE
```

**Comment by hadley** [comment]
Looks like this will have to be handled on the stringi side as the parsing logic is more complex than just matching in to  `stringi::stri_locale_list()`.

**Comment by Kodiologist** [comment]
I'm not familiar with `stringi`, but it sounds like it has two problems: it accepts an unrecognized locale without warning, and it doesn't support the standard C locale.

**Comment by gagolews** [comment]
In ICU, the 'C' locale is named 'en_US_POSIX'. I will create an alias for it.
In the next release of stringi, a warning will be emitted on unknown locales.

**Comment by Kodiologist** [comment]
Sounds like a good plan.
