### ISSUE TITLE
Libicui problem

### ISSUE THREAD

**Issue by bshor** [tidyverse/stringr#441]
I am running Garuda Linux, an Arch-derivative rolling release distro, with the latest 5.17.3 kernel. R (v4.1.3) and RStudio works great on my setup, but today I got hit with this odd error when trying to load stringr:

```
Error: package or namespace load failed for ‘stringr’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib/R/library/stringi/libs/stringi.so':
  libicui18n.so.70: cannot open shared object file: No such file or directory

```

Any ideas?

*Update* I figured out how to fix this. I needed to recompile the underlying stringi function, which I did by removing and reinstalling stringi. All good. I guess libicu was updated while stringi was still compiled against the old version, leading to this error.

**Comment by cbrnr** [comment]
I keep running into this problem (I'm on Arch), but I guess there's nothing that stringr can do here (I assume it cannot trigger a stringi update). I'll just have to find this issue when it happens again in the future 😄.
