### ISSUE TITLE
Please consider reinstating 'From base R' vignette

### ISSUE THREAD

**Issue by MattCowgill** [tidyverse/stringr#442]
The vignette that shows `{stringr}` functions aligned with their base R equivalents is extremely useful. I check it often. It appears to have been removed. Please consider reinstating it! 

https://stringr.tidyverse.org/articles/from-base.html

**Comment by MattCowgill** [comment]
I can see that the RMd is still in this repo (https://github.com/tidyverse/stringr/blob/main/vignettes/from-base.Rmd) but I guess something is stopping it from displaying on the pkgdown site?

**Comment by hadley** [comment]
Looks fine in dev version: https://stringr.tidyverse.org/dev/, so it'll get fixed once I release stringr.

**Comment by hadley** [comment]
Hmmm, might be worth a quick website patch since the release might be a while.

**Comment by hadley** [comment]
Ooooh it has never been in the CRAN version, so this really does need a release.

**Comment by MattCowgill** [comment]
Thank you @hadley !
