### ISSUE TITLE
Export functions to remove empty or NA strings?

### ISSUE THREAD

**Issue by mrcaseb** [tidyverse/stringr#443]
I have noticed that stringi ships functions to remove empty and/or NA strings from a vector (see `?stri_remove_empty`). I wonder if stringr could export them?

``` r
vec <- c('a', NA_character_, 'b', '')

stringi::stri_remove_empty(vec)
#> [1] "a" NA  "b"
stringi::stri_remove_na(vec)
#> [1] "a" "b" ""
stringi::stri_remove_empty_na(vec)
#> [1] "a" "b"
```

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think this is a little to special purpose for strignr: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
