### ISSUE TITLE
Make `str_wrap()` insert e.g. `<br>` instead of `\n`?

### ISSUE THREAD

**Issue by SchmidtPaul** [tidyverse/stringr#447]
Would it be worthwhile to have an argument in `str_wrap` that lets you choose other separators than `\n`? I usually use `str_wrap() %>% str_replace_all("\n", "<br>")` when working with [{ggtext}](https://wilkelab.org/ggtext/), which provides simple Markdown and HTML rendering for ggplot2:

``` r
library(tidyverse)
library(ggtext)

long_label <-
  "The series centers on the various incarnations of Link, a courageous young Hylian man, with pointy, elf-like ears; and Princess Zelda, a magical princess that is the mortal reincarnation of the goddess Hylia; as they fight to save the magical land of Hyrule from Ganon, an evil warlord turned demon king, who is the principal antagonist of the series."

lab_dat <- tibble(label = str_wrap(long_label, 50) %>% str_replace_all("\n", "<br>"),
                  mpg = 20,
                  cyl = 6)

ggplot(mtcars, aes(mpg, cyl, label = label)) +
  geom_richtext(data = lab_dat)
```

![](https://i.imgur.com/SySanmG.png)

<sup>Created on 2022-07-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
This feels a bit too specialised for stringr to me, but it's a great place make your own function:

```R
str_wrap_br <- function(x, width) {
  x <- str_wrap(x, width)
  str_replace_all(x, "\n", "<br>")
}
```
