### ISSUE TITLE
Lazy matching strange behavior of regexp in stringr

### ISSUE THREAD

**Issue by mkvasnicka** [tidyverse/stringr#450]
Hi!

I would expect that the following code should return `"<a href ... >"` only. 

```{r}
s <- '<h1>Title</h1><a href="https://stringr.tidyverse.org/">link</a><p>text</p>'
str_extract(s, "<.*?href.*?>")
```

However, it returns `"<h1>Title</h1><a href=\"https://stringr.tidyverse.org/\">"`, i.e., the first `.*?` is greedy while the second `.*?` is lazy.

Based on a similar code I used, I think both `.*?` were lazy in the past. Is it a bug or a feature I don't understand?

Best wishes,
Michal

**Comment by gagolews** [comment]
An even simpler reproducible example:

```r
s <- "<<A>>"
stringi::stri_extract_first_regex(s, "<.*?A.*?>")
## [1] "<<A>"
```

But base R has the same behaviour:

```r
> regexec("<.*?A.*?>", s, perl=TRUE)
[[1]]
[1] 1
attr(,"match.length")  # i.e., "<<A>"
[1] 4
```

The matching algorithm goes as follows: once the first `<` is matched, the regexp engine tries to pinpoint `A`, but *without restarts* if `A` is found, i.e., without looking back where there is a match. So the matching is only performed left-to-right.

It's a feature, not a bug.

Example workaround:

```r
stringi::stri_extract_first_regex(s, "<[^<]*?A.*?>")
## [1] "<A>"
```

**Comment by hadley** [comment]
Thanks for the explanation @gagolews!

**Comment by mkvasnicka** [comment]
Thanks. I see I still have to improve my understanding of regex. :-)

**Comment by gagolews** [comment]
Yeah, this was a tricky one..
