### ISSUE TITLE
[Feature request] function to segment strings into substrings of width `n` or less

### ISSUE THREAD

**Issue by wurli** [tidyverse/stringr#461]
`str_wrap()` almost hits the spot but not quite. I'd propose an alternative, perhaps `str_segment()` which does the following:

* Breaks a string into a character vector of several 'segments' instead of inserting delimiters like `\n`

* Breaks at a user-specified separator, similarly to `strsplit()`, but only where needed

Why? This is functionality I've reached for fairly frequently in the past but have ended up having to implement myself. E.g. a simple use case is to break a string into segments of 280 characters or less, and to break at `"\\b\\.\\s+"` (i.e. break a string into valid tweets by sentence). It would be a really nice convenience to see this in stringr, especially as this package seems to be getting some love currently.

E.g. this function would have the following behaviour:

```
str_segment("This is a fairly short string", n = 10, sep = " ")
#> [[1]]
#> [1] "This is a" "fairly"    "short"     "string"   

# The big space and the new line would be lost using `str_wrap()`
str_segment("This string has some       big spaces\nand a new line", n = 15, sep = "\s+")
#> [[1]]
#> [1] "This string has" "some       big"  "spaces\nand a"   "new line"    
```

**Comment by wurli** [comment]
Thanks for the response - and for the elegant example! 

Your implementation is slightly different to what I had in mind; I was envisioning that each segment would be <= `width` but this breaks that rule:
``` r
str_segment_1("   This is a fairly short string   ", width = 10) |>
  print() |>
  nchar()
#> [1] "   This is"   "a fairly"     "short string" ""            
#> [1] 10  8 12  0
```

I'll put an example implementation at the end.

## Use-Cases
> it also seems like a rather special case, so I'm somewhat sceptical that stringr is the right home for it

Fair point. Most of the use-cases I can think of are variations of text-wrapping problems, but I think these problems are quite common, and there's a lot of them that `str_wrap()` can't solve since you can't specify appropriate places to insert breaks, and it always effectively applies `str_squish()` before running. For example:

* Wrapping where whitespace is significant. E.g. wrapping blocks of code, or nested bullet lists. In both cases you'd probably want to specify `sep = "\n"`. 
  * Thinking about it some more, if you want to specify `sep` you might also be interested in changing specifying which characters should be counted too. See the code at the end for an example.
* [Greedy string wrapping](https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap#Minimum_number_of_lines) would become trivial to implement as an alternative to the Knuth-Plass algorithm implemented in `str_wrap()`

**However** I see your point and having thought a bit more I might agree - so if you want to ignore the rest of this comment that's fine with me.

## Example implementation 
This is pretty grim compared to your implementation, but seems to work as intended:
``` r
str_segment_1 <- function(x, width = 80, break_at = "\\s+", count_at = ".") {
  
  # Might be better to allow segments with more than `width` chars in
  # such cases... ?
  stopifnot(all(str_count(strsplit(x, break_at)[[1]], count_at) <= width))
  
  break_pos <- invert_match(str_locate_all(x, break_at)[[1]])
  break_pos[break_pos < 0] <- nchar(x) + 1
  
  out <- character()
  
  repeat {
    is_new_seg <- vapply(
      break_pos[, "end"], 
      function(end) str_count(str_sub(x, min(break_pos[, "start"]), end), count_at) <= width,
      logical(1)
    )
    new_seg <- break_pos[is_new_seg, , drop = FALSE]
    
    out <- c(out, str_sub(x, new_seg[, "start"][1], new_seg[, "end"][nrow(new_seg)]))
    
    if (all(is_new_seg)) {
      break
    }
    
    break_pos <- break_pos[!is_new_seg, , drop = FALSE]
  }
  
  out
}

str_segment_1("This is a fairly short string.", width = 10)
#> [1] "This is a" "fairly"    "short"     "string."
str_segment_1("   This is a fairly short string   ", width = 10)
#> [1] "   This is" "a fairly"   "short"      "string   "
str_segment_1("This string has some       big spaces\nand a new line", width = 15)
#> [1] "This string has"   "some       big"    "spaces\nand a new"  "line"
```

### Extra feature: `count_at`
I think this is what would make this function really useful, but it took the creation of this issue to help me think of it. The default, `count_at = "."` would provide the same functionality as already discussed. But it could also be used to get much greater control over how segmenting should be performed. Do you want `width` or less words? Use `count_at = "\\s+"`. Do you want `width` or less linebreaks? Use `count_at = "\n"`. Some more specific potential use-cases:

* Break a body of text into pages where each page has at most 700 words using `width = 699`, `break_at = "\\s+"` and `count_at = "\\s+"`
* Break a poem into pages where each page has at most 40 lines using `width = 39`, `break_at = "\n"` and `count_at = "\n"`
* Break a bullet list into sections where each section has at most 100 lines but bullets don't overflow between sections using `width = 99`, `break_at = "(?<=\n)\\*"` and `count_at = "\n"`

Thanks again!

**Comment by gagolews** [comment]
Note that - as long as there are no newlines, you can pass `normalise=FALSE` to `stri_wrap`.

```
> stringi::stri_wrap("This string has some       big spaces\tbut zero\tnew     lines", width=15, normalise=FALSE)
[1] "This string has"  "some       big"   "spaces\tbut zero" "new     lines"  
```

With `stri_wrap`, it is also possible to switch to the greedy algorithm.

**Comment by wurli** [comment]
Thanks, I wasn't aware you could get this behaviour with `str_wrap()`. @hadley perhaps you're right that this is just something which users should go to another package - probably {stringi} - for.

**Comment by hadley** [comment]
Yeah, given that stringi already provides all these options, that's the place to go 😄
