### ISSUE TITLE
str_replace (and potentially other functions) should be more clear about the fact that they only perform their actions on the first matched pattern

### ISSUE THREAD

**Issue by deschen1** [tidyverse/stringr#466]
Might be that I'm not fully understanding the documentation of e.g. `str_replace`, but it would be great if the help would be more clear about the fact that only the first found pattern will be replaced (similar things apply to other functions):

`str_replace("aba", "a", "c")` returns `cba`, while some users might expect `cbc`.

**Comment by hadley** [comment]
All ready fixed in the dev version, e.g. https://stringr.tidyverse.org/dev/reference/str_replace.html
