### ISSUE TITLE
`str_pad` with Unicode characters pads incorrectly

### ISSUE THREAD

**Issue by mwip** [tidyverse/stringr#467]
Triggered by a bug reported here https://github.com/mwip/beautifyR/issues/14, I found that `str_pad` omits characters, when `string` includes a Unicode character. 

Please see this minimal, reproducible example:
```R
> x <- "✅                "
> nchar(x)
[1] 17
> nchar(stringr::str_pad(string = x, width = 18, side = "right", pad = " "))
[1] 17
```

We see that `x` has 17 characters to begin with. After padding it to 18 using `str_pad()`, it still registers as 17 `nchar` instead of the expected 18.

Is this intended behavior or a bug? If intended, is there a proper workaround?

```
R       4.2.1
stringr 1.4.1
```

**Comment by gagolews** [comment]
Please note that the underlying `stringi::stri_pad` pads with respect to `stringi::stri_width`, not the number of Unicode code points.

**Comment by mwip** [comment]
Thanks for the clarification. That helps a lot. 

So, this _is_ intended behavior and I should be using `stri_width` in favor of `nchar` when determining the padding width?

Forgive me, when I missed something.

**Comment by hadley** [comment]
Yes, or `str_width()` which wraps `stri_width()`.

**Comment by gagolews** [comment]
> So, this _is_ intended behavior and I should be using `stri_width` in favor of `nchar` when determining the padding width?

Apologies for a delayed response; 

"Should" is a strong word ;) — but yes, stri_width tries to do its best to guesstimate the display width. It is not perfect though (as stated in its manual).
