### ISSUE TITLE
str_squish() replaces single instances of mid-string \n and \r with space

### ISSUE THREAD

**Issue by jzadra** [tidyverse/stringr#477]
I understand that \n and \r are technically whitespace characters.  

However, the behavior of str_squish() where it replaces a single, mid-string occurance of \n or \r with a single whitespace is unexpected.

str_trim() does not replace mid-string occurances of these, as expected:
> `str_trim("hello\nworld")`
[1] "hello\nworld"

str_squish() is specifically for removing **repeated** whitespace.  Therefore, shouldn't `str_squish("hello\n\nworld") should produce "hello\nworld"?

> `str_squish("hello\nworld")`
[1] "hello world"
> `str_squish("hello\n\nworld")`
[1] "hello world"

**Comment by hadley** [comment]
I've tweaked the docs to make it more clear that this is the expected behaviour.

**Comment by LukasWallrich** [comment]
I also got caught out by this, so thanks for editing the docs. However, might it be worth having a parameter that allows for either behaviour?

```r
str_squish_mild <- function(string) {
  str_replace_all(string, "(\\s)\\1+", "\\1") %>% str_trim()
}
```

**Comment by LukasWallrich** [comment]
Ok, this is more complicated, so I am withdrawing my suggestion. In the use intended by @jzadra and me, repeated `\r\n` should also be replaced by a single new line ... which makes it harder to have a consistent alternative, so this should probably just stay as is. Just in case it is helpful for anyone who comes across this in the future, here a version of the function that achieves this.

```r
str_squish_mild <- function(string) {
  str_replace_all(string, "(\\s)(\\s)(\\1\\2)+", "\\1\\2") %>%
  str_replace_all("(\\s)\\1+", "\\1") %>% str_trim()
}
```
