### ISSUE TITLE
Feature request: Groups_only=TRUE

### ISSUE THREAD

**Issue by KasperThystrup** [tidyverse/stringr#478]
Thank you for a really usefull Regex toolbox!

I usually use this tool over the inbuild grep-like functions.

One feature I would really enjoy would be for str_match(_all) to return group matches only / omit the full pattern match, so that you can build a pattern which is directly translatable into a tibble.

Currently, my go-to workflow for str_match_all is
```
my_string <- "/path/to/convert/into/frame/this/collosal_5/is/my_pattern_42.ext"
stringr::str_match(
  string = my_string,
  pattern ="this/(?<type>\\w+_\\d)/is/(?<sample>my_pattern_\\d+)\\.ext"
) %>%
  tibble::as_tibble() %>%
  dplyr::select(-V1)
```

It would be nice to have an option for e.g.
```
stringr::str_match_all(
  string = my_string,
  pattern ="this/(?<type>\\w+_\\d)/is/(?<sample>my_pattern_\\d+)\\.ext",
  groups_only = TRUE
) %>%
  tibble::as_tibble()
```

To yield:
```
# A tibble: 1 × 2
  type       sample       
  <chr>      <chr>        
1 collosal_5 my_pattern_42
```

**Comment by KasperThystrup** [comment]
I can see that using `str_match` instead of `str_match_all` actually enables you to skip the `as.data.frame` step, however you would still have to deselct the full_match column, if it's not of interest. Editted the request accordingly

**Comment by hadley** [comment]
Given that most applications of this pattern involve working with an existing columns and create new columns, we decided to implement this in tidyr:

``` r
library(tidyr)

df <- tibble(x = "/path/to/convert/into/frame/this/collosal_5/is/my_pattern_42.ext")

df %>% 
  separate_wider_regex(
    x,
    patterns = c(
      ".*/this/",
      type = "\\w+_\\d",
      "/is/",
      sample = "my_pattern_\\d+",
      "\\.ext"
    )
  )
#> # A tibble: 1 × 2
#>   type       sample       
#>   <chr>      <chr>        
#> 1 collosal_5 my_pattern_42
```

<sup>Created on 2022-11-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by KasperThystrup** [comment]
Thx a bunch! Didn't realize tidyr had regex functionality as well. It's really nice to have an one-liner option for pattern capture!!
