### ISSUE TITLE
General function to clean variable names

### ISSUE THREAD

**Issue by jospueyo** [tidyverse/stringr#481]
After a `pivot_longer`, I usually have to do several operations to clean up the names before plotting, especially if I used `janitor::clean_names()` when the data was loaded. Most often I use a combination of `str_to_sentence(name)` and `str_replace_all("_"," ", name)`. So, I usually create a wrap up functions which combines both:
```
str_cleanup <- function (string, locale = "en") 
{
  string <- str_to_sentence(string)
  str_replace_all("_", " ", string)
}
```
Of course, other options might be considered if implemented. I am willing to do a pull request if you think this would be useful.

IMO, it may also be an option directly implemented in pivot_longer.

Looking forward to your comments!

**Comment by hadley** [comment]
I think unfortunately this is out of scope for stringr because we're trying (as much as possible) to keep the functions fairly generally applicable and there's a lot of variation in how folks want to name their variables.
