### ISSUE TITLE
Add str_lengths function?

### ISSUE THREAD

**Issue by LukasWallrich** [tidyverse/stringr#485]
I use string manipulations regularly and sometimes find myself missing a `lengths()` equivalent, for example to subset strings longer/shorter than a given length. Once I learned how to use `Vectorise`, this is trivial to achieve with a wrapper around `str_length` - but I was wondering whether such a `str_lengths` function would be a worthwhile addition to stringr?

```r
responses <- c("Hello", "Hi", "Too verbose")
str_lengths <- Vectorize(str_length, USE.NAMES = FALSE)
str_lengths(responses)
```

**Comment by hadley** [comment]
`str_length()` is already vectorised 😄 

``` r
library(stringr)

responses <- c("Hello", "Hi", "Too verbose")
str_length(responses)
#> [1]  5  2 11
```

<sup>Created on 2022-12-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by LukasWallrich** [comment]
Thanks - rather silly 😄. I relied on the documentation that usually highlights arguments that are vectorised - but could have just tried it ...
