### ISSUE TITLE
Feature request: `sep` argument in `str_dup`.

### ISSUE THREAD

**Issue by maellecoursonnais** [tidyverse/stringr#487]
I was going through this [SO question](https://stackoverflow.com/questions/74810135/is-there-an-r-function-that-will-repeat-a-number-limited-by-for-x-number-of), and thought that it might be useful to add an optional `sep` argument to `str_dup`.

For instance, in the case of the SO question the OP wants to repeat a string and add `;` between every repeated value.
```r
n = 3
input = c(67L, 24L, 72L, 3L)
expected_output = c("67;67;67", "24;24;24", "72;72;72", "3;3;3")
```
So far, what one can do is:
```r
library(stringr)
library(purrr)
map_chr(input, ~ str_flatten(rep(.x, each = n), ";"))
#[1] "67;67;67" "24;24;24" "72;72;72" "3;3;3"
```
Or in base R:
```r
sapply(input, \(x) paste(rep(x, n), collapse=";")) 
```
But what about a simple `str_dup` call?
```r
str_dup(input, n, sep = ";")
```

**Comment by hadley** [comment]
I'd implement this by adding an extra `sep` argument that defaults to `NULL`. When `sep` is not `NULL`, fallback to using `rep()` to repeat the string then paste together with `collapse = sep`.

You'll also need to use `check_string()` to give an informative error if `sep` is not a string.
