### ISSUE TITLE
Incorrect deprecation message for `str_view_all`

### ISSUE THREAD

**Issue by cgoo4** [tidyverse/stringr#488]
```
> lifecycle::last_lifecycle_warnings()
[[1]]
<warning/lifecycle_warning_deprecated>
Warning:
`str_view()` was deprecated in stringr 1.5.0.
ℹ Please use `str_view_all()` instead.
---
Backtrace:
 1. stringr::str_view_all(...)
```

**Comment by matthewjnield** [comment]
I noticed the deprecation warning for str_view_all() today as well, and have submitted pull request #490 to correct it.

Example:

#> library(stringr)
#> str_view_all(string = "abc", pattern = "b")
#> Warning: `str_view()` was deprecated in stringr 1.5.0.
#> ℹ Please use `str_view_all()` instead.
#>  [1] │ a\<b\>c

**Comment by matthewjnield** [comment]
After merging pull request #490, the deprecation warning displayed when str_view_all() is called is now correct:

``` r
remotes::install_github(repo = "tidyverse/stringr", ref = "741300390b042889f5b60578ed7e0f9ce41963c5", quiet = TRUE)
library(stringr)
str_view_all(string = "abc", pattern = "b")
#> Warning: `str_view_all()` was deprecated in stringr 1.5.0.
#> ℹ Please use `str_view()` instead.
#> [1] │ a<b>c
```
