### ISSUE TITLE
Keep "I" capitalized in `str_to_sentence` for the "en" locale

### ISSUE THREAD

**Issue by ZIBOWANGKANGYU** [tidyverse/stringr#498]
Currently, the single upper-case letter "I" is changed to "i" if it appears in the middle of a sentence. 
```
> stringr::str_to_sentence("THIS IS WHAT I MEAN!")
[1] "This is what i mean!"
```
It might be a good idea to keep "I" capitalized. Sorry if this discussion is more suitable for the `stringi` package.

**Comment by hadley** [comment]
This function is a very thin wrapper around `stri_trans_totitle()`, so stringi would be the write place to file an issue.
