### ISSUE TITLE
Misprint in documentation for str_split()

### ISSUE THREAD

**Issue by presnell** [tidyverse/stringr#500]
In the section describing the argument `n`, there is a `split_split()` that should be `str_split()`.

**Comment by feinleib** [comment]
I see two additional fixes in the Examples section.

1. The comment for `str_split_1()` is missing the second underscore:

```
# If you want to split a single string, use `str_split1`
```

2. The names of the functions are written differently in each comment. These should be made consistent with each other. 

```
# If you want to split a single string, use `str_split1`
# Use fixed to return a character matrix
# str_split_i extracts only a single piece from a string
```

My understanding of the [relevant section of the Tidyverse Style Guide](https://style.tidyverse.org/documentation.html#r-code) is that the correct format for these comments is backticked, with trailing parentheses:
```
`str_split_1()`     `str_split_fixed()`     `str_split_i()`
```
