### ISSUE TITLE
`str_split_1` errors for empty character vector

### ISSUE THREAD

**Issue by jl5000** [tidyverse/stringr#504]
It would be useful if it just returned the original empty vector.

``` r
stringr::str_split_1(character(), " ")
#> Error in `stringr::str_split_1()`:
#> ! `string` must be a single string, not an empty character vector.
```

<sup>Created on 2023-03-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
I think the existing behaviour is correct because it requires a character vector of length 1.
