### ISSUE TITLE
Underscore in named group matching

### ISSUE THREAD

**Issue by DSLituiev** [tidyverse/stringr#506]
I am trying to match a named group and running into a behaviour that does not seem to be properly documented.

```r
filnames = c("a","b", "c")

pattern_regex <- (?<my_variable>[a-zA_\\-]+)"

str_match(filnames, pattern_regex)
```

```
Error in stri_match_first_regex(string, pattern, opts_regex = opts(pattern)) : 
  Invalid capture group name. (U_REGEX_INVALID_CAPTURE_GROUP_NAME, context= ...
```
There is no documentation that says underscores are unsupported, and given it's a common practice in other languages, like python `re`, I assumed it should have worked. The error message is not helpful either

**Comment by gagolews** [comment]
Please see the documentation of the underlying `stringi` package:

https://stringi.gagolewski.com/rapi/about_search_regex.html:

> `(?<name>...)`:    Named capture group, where name (enclosed within the angle brackets) is a sequence like `[A-Za-z][A-Za-z0-9]*`

**Comment by hadley** [comment]
Thanks @gagolews!
