### ISSUE TITLE
Documentation for str_subset & str_detect imply pattern can be empty, but that gives an error

### ISSUE THREAD

**Issue by yadbor** [tidyverse/stringr#508]
The documentation for str_detect and str_subset should be updated to say that pattern cannot be empty or boundary().

Currently both say "An empty pattern, "", is equivalent to boundary("character")", implying that they will accept a boundary() as the pattern, but this gives an error as below.

```
> fruit <- c("apple", "banana", "pear", "pineapple")
> str_subset(fruit, "")
Error in `str_subset()`:
! `pattern` can't be the empty string (`""`).

> fruit <- c("apple", "banana", "pear", "pineapple")
> str_subset(fruit, boundary("character"))
Error in `str_subset()`:
! `pattern` can't be a boundary.
```

**Comment by hadley** [comment]
To fix this documentation issue for TDD, you'll need to identify the five functions that forbit both empty and boundary patterns and create a new `@param pattern` docstring for them to inherit from instead of `str_detect()`.
