### ISSUE TITLE
str_replace_all with multiple replacements

### ISSUE THREAD

**Issue by Close-your-eyes** [tidyverse/stringr#516]
The result of `stringr::str_replace_all("abcd", pattern = c("a" = "d", "d" = "x"))` is "xbcx". That means, patterns are replaced one after the other: 'a' first becomes 'd' and in second round 'd' becomes 'x'. So, 'a' becomes 'x'.

What do I have to do to get "dbcx" as result?

I expect it is not possible with stringr::str_replace_all. But, is there another function to do it and if not, is the behaviour I desire too weird to be covered by stringr::str_replace_all?

**Comment by hadley** [comment]
I don't know of any easy way to do that, sorry.

**Comment by allenbaron** [comment]
You could add another element to your pattern vector using a character that is not found in the input to `stringr::str_replace_all()`.

Example using `%`:
``` r
stringr::str_replace_all("abcd", pattern = c("a" = "%", "d" = "x", "%" = "d"))
#> [1] "dbcx"
```

<sup>Created on 2024-07-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
