### ISSUE TITLE
options(stringr.html = TRUE) does not work

### ISSUE THREAD

**Issue by lucavalery** [tidyverse/stringr#534]
Since stringr 1.5.0,  `str_view()` generates, by default, an ANSI output in the console; with the option  `html = TRUE`, a html output (in the Viewer in an .R script, in html in a rendered markdown).
The [documentation of stringr::str_view()](https://stringr.tidyverse.org/reference/str_view.html) specifies that it is possible to set the glopal option `stringr.html = TRUE` to avoid specifying the option `html = TRUE` in every call to `str_view()` (thus reproducing a useful default behaviour of the older versions of `stringr`):

![stringr_docu](https://github.com/tidyverse/stringr/assets/27213536/bea6dace-dffd-4f71-a606-6c12f1301141)

However, this global option does not seem to work.

This code:
```
library(stringr)
options(stringr.html = TRUE)
c("a cat", "that dog", "a similar cat", "the penguin") |> str_view("cat")
```
still causes the default behaviour of printing, in the Console,
![bad_cat](https://github.com/tidyverse/stringr/assets/27213536/6ac13c8d-ea63-426c-be5a-34cfbe082120)

Whereas specifying the option in a single call does work, with the html in the Viewer:
```
c("a cat", "that dog", "a similar cat", "the penguin") |> str_view("cat", html = TRUE)
```
![good_cat](https://github.com/tidyverse/stringr/assets/27213536/0e7ed23e-24fc-42f6-93db-40ad3aa17a3d)

The Posit community helped to verify that indeed `str_view()` does not seem to call at all `stringr.html`, and that that sentence in the documentation is the only place this option is mentioned in the repo. Therefore, this could be a bug.

I am working on Posit Cloud (R version 4.3.1 and RStudio Pro 2023.09.1, Build 494.pro2), stringr 1.5.0. Thank you in advance for your attention!

**Comment by hadley** [comment]
That looks like a bit of documentation I forgot to update 😞  If you want this behaviour you can just make your own wrapper in an early chunk:

```R
str_view <- function(...) {
  stringr::str_view(..., html = TRUE)
}
```
