### ISSUE TITLE
Strings not properly splitting into separate list elements?

### ISSUE THREAD

**Issue by AustinFournierKL** [tidyverse/stringr#541]
Hello, I'm having a weird issue with the way that str_split is producing its output. Suppose I use something like this:

`x = str_split("OneXTwoXThree", "X")
`
Ideally, I'd want this to give me a list with 3 elements, "One," "Two", and "Three", such that I can inspect each of these words individually to see if they appear in a different dataset I have elsewhere. From what I've read about how lists worked, I should be able to extract an element by subsetting a list like a vector; for example, I should be able to get "Two" by following up the previous code with `x[2]`.

However, in practice, str_split is giving me a list with a single, hard-to-use element. Thus, `x[1]` returns ` "One"   "Two"   "Three"`, and `X[2]` returns ` NULL`.

Is this the intended behavior of this function? If so, do you know a workaround that will allow me to access individual words from within the list?

**Comment by werkstattcodes** [comment]
A quick answer below.  I believe such questions are better placed at Stackoverflow or posit's community forum.

> x = str_split("OneXTwoXThree", "X")
> length(x)
[1] 1
> #peek into the list by using [[]]
> x[[1]][1]
[1] "One"
> x[[1]][2]
[1] "Two"
> x[[1]][3]
[1] "Three"
> #since x is of lenght 1 there is no 2nd element
> x[2]
[[1]]
NULL

**Comment by arnaudgallou** [comment]
`stringr::str_split()` returns a list, this is the normal behavior. If you have one string to split and want to output each element in a single character vector, you can use `stringr::str_split_1()`.

``` r
stringr::str_split("OneXTwoXThree", "X")
#> [[1]]
#> [1] "One"   "Two"   "Three"

stringr::str_split_1("OneXTwoXThree", "X")
#> [1] "One"   "Two"   "Three"
```

<sup>Created on 2024-03-27 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by AustinFournierKL** [comment]
Thank you very much for the help! @werkstattcodes I agree Github would make sense given full understanding of the situation, but since my reading on lists caused me to misunderstand how they were intended to behave at the time I suspected I was looking at a glitch.
