### ISSUE TITLE
[Feature request] allow `str_wrap()` to wrap into n segments of equal length

### ISSUE THREAD

**Issue by DanChaltiel** [tidyverse/stringr#572]
Hi,

When using `str_wrap()` for plot captions, it is often useful to fix the number of lines rather than the number of characters per line.

For that, I'm using the following code: 

``` r
library(tidyverse)

caption = "The dots and whiskers represent the median and the 25th and 75th percentiles of the X coefficient among the N simulated trial replicates."

p = ggplot(mtcars, aes(x=disp, y=disp)) +
  geom_point() +
  coord_fixed()  

p + labs(caption=caption) #the caption overflows
```

![](https://i.imgur.com/1etDIzE.png)

``` r
p + labs(caption=str_wrap(caption, nchar(caption)/2))
```

![](https://i.imgur.com/pVEnpYs.png)

<sup>Created on 2024-09-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

However, as you can see, you need to refer to the `caption` object twice, which is not handy, and the output is not perfect when the split happens near long words (the output has 3 lines instead of 2, don't have a workaround for that yet).

Do you think `str_wrap()` could support an additional argument to specify the number of lines instead of `width`?

**Comment by hadley** [comment]
`str_wrap()` is a pretty thin wrapper around `stri_wrap()`.  But think the challenge will be, as you have identified, figuring out the right way to split into the correct number of lines.
