### ISSUE TITLE
Function to sanitize strings

### ISSUE THREAD

**Issue by jdonland** [tidyverse/stringr#574]
Could `stringr` implement something like `fedmatch::clean_strings()` or `lhmet/rinmetxls::str_santize()` to strip or replace special characters, reserved filenames, trailing periods and spaces, weird Unicode characters, etc. from a character vector all at once?

**Comment by danalvarez** [comment]
Although it doesn't do everything, take a look at https://github.com/tidyverse/stringr/issues/149 if you haven't already

**Comment by hadley** [comment]
@danalvarez thanks for the pointer!
