### ISSUE TITLE
Add support for named capture groups

### ISSUE THREAD

**Issue by mplourde** [tidyverse/stringr#71]
Base R supports Python-style named capture groups with the `perl` option.

``` r
pat <- '-(?<food>[a-z]+)-'
string <- '-bacon-'
regexpr(pat, string, perl=TRUE)
```

It would be great to be able to use these patterns with **stringr**. Right now, a pattern such as this generates an error:

``` r
str_match_all(string, regex(pat))
str_match_all(string, perl(pat))
# Error in stri_match_all_regex(string, pattern, cg_missing = "", omit_no_match = TRUE,  : 
#   Syntax error in regexp pattern. (U_REGEX_RULE_SYNTAX)
```

**Comment by gagolews** [comment]
see https://github.com/Rexamine/stringi/issues/153

**Comment by hadley** [comment]
Thanks to the fix in stringi, this now just works in stringr:

``` r
library(stringr)

str_match("-bacon-", '-(?<food>[a-z]+)-')
#>                food   
#> [1,] "-bacon-" "bacon"
str_match_all("-bacon-", '-(?<food>[a-z]+)-')
#> [[1]]
#>                food   
#> [1,] "-bacon-" "bacon"
```

<sup>Created on 2021-08-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
